### ISSUE TITLE
NCCL error occurs when RaySGD: TorchTrainer uses GPU under multiple nodes, why?

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#13480]
I ran a RaySGD: TorchTrainer program (https://docs.ray.io/en/latest/raysgd/raysgd.html) to test distributed parallel training.
In trainer1=TorchTrainer(), I set num_workers=6,use_gpu=True, backend="nccl". 
The Ray cluster has one master and two slaves. After submission, I can see that there are 3 processes in each of the 2 slaves, and the GPU is also being used. But the operation has been reporting errors as follows:
-------------------edite line----------------
File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/training_operator.py", line 165, in <listcomp>
    for model in models
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 333, in __init__
    self.broadcast_bucket_size)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 549, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8
-------------------edite line----------------
I thought it might be a problem with the NCCL library that comes with torch, and then I ran a torch program（no ray） that uses GPUs under multiple nodes. The program also uses NCCL to implement All-Reduce, but no error was reported.
And I will set backend="gloo", TorchTrainer can also run normally.
So it should not be NCCL that has the problem, but RaySGD: TorchTrainer has a problem when using NCCL?
Are there any other settings required here?
In addition, when I start the Ray cluster on only one node and submit the above code, everything is OK.
This problem confuses me, can you help me solve it?

**Comment by krfricke** [comment]
cc @amogkam

**Comment by amogkam** [comment]
Hey @Matrix-World, could you share the full stack trace?

Also, could you create an initialization hook and add it to your `TorchTrainer` like so:
```
def initialization_hook():
    print("NCCL DEBUG SET")
    # Need this for avoiding a connection restart issue
    os.environ["NCCL_SOCKET_IFNAME"] = "^docker0,lo"
    os.environ["NCCL_LL_THRESHOLD"] = "0"
    os.environ["NCCL_DEBUG"] = "INFO"

trainer = TorchTrainer(
    training_operator_cls=MyTrainingOperator,
    initialization_hook=initialization_hook,
    ...)
```

I believe you might be getting the same error as https://github.com/ray-project/ray/issues/11675. Are you running on an Azure cluster?

**Comment by Matrix-World** [comment]
> 
> 
> Hey @Matrix-World, could you share the full stack trace?
> 
> Also, could you create an initialization hook and add it to your `TorchTrainer` like so:
> 
> ```
> def initialization_hook():
>     print("NCCL DEBUG SET")
>     # Need this for avoiding a connection restart issue
>     os.environ["NCCL_SOCKET_IFNAME"] = "^docker0,lo"
>     os.environ["NCCL_LL_THRESHOLD"] = "0"
>     os.environ["NCCL_DEBUG"] = "INFO"
> 
> trainer = TorchTrainer(
>     training_operator_cls=MyTrainingOperator,
>     initialization_hook=initialization_hook,
>     ...)
> ```
> 
> and then share the full logs as well.
> 
> I believe you might be getting the same error as #11675. Are you running on an Azure cluster?

Thank you for your reply, I am not running on Azure cluster, I am deploying my own machine. This problem has been solved, and the same version of ray needs to be installed on each node.

**Comment by amogkam** [comment]
Ah got it- glad to hear it's been resolved :)
