### ISSUE TITLE
[core] Fractional GPUs do not seem to work with tensorflow

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#13680]
<!--Please include [tune], [rllib], [autoscaler] etc. in the issue title if relevant-->

### What is the problem?

Ray: 1.1.0 (but reproduced on latest wheels)
Tensorflow: 2.3.2
Cuda: 10.1
Cluster: Single node p2.xlarge instance (NVIDIA K80 GPU), docker image `anyscale/ray:latest-gpu`

When using fractional GPUs with tensorflow, workers run into OOM errors on the GPU. Eventually (some of the) tasks return, but not without throwing hundreds/thousands of error messages.

Program execution is non-deterministic, sometimes it works and sometimes it hangs forever. A workaround seems to be to use `num_gpus=0.24` instead of `0.25`, so maybe there is a rounding error somewhere?


### Reproduction (REQUIRED)

```
import ray
import time

import tensorflow as tf


ray.init(address="auto")

@ray.remote(num_gpus=0.25)
def f():
    print("Num GPUs Available: ",
          len(tf.config.experimental.list_physical_devices('GPU')))

    with tf.device('/GPU:0'):
        a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

    c = tf.matmul(a, b)
    print("Result", c)

    time.sleep(1)

# The four tasks created here can execute concurrently.
ray.get([f.remote() for _ in range(4)])
```

Output:

```
2021-01-25 03:36:31.075006: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                             
2021-01-25 03:36:32,672 INFO worker.py:657 -- Connecting to existing Ray cluster at address: 172.31.31.51:6379                                                                                
(pid=4224) 2021-01-25 03:36:33.376736: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                  
(pid=4240) 2021-01-25 03:36:33.918359: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                  
(pid=4242) 2021-01-25 03:36:33.995977: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                  
(pid=4241) 2021-01-25 03:36:34.075237: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                          
(pid=4261) 2021-01-25 03:36:34.638970: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                          
(pid=4284) 2021-01-25 03:36:34.812830: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                          
(pid=4240) 2021-01-25 03:36:38.861354: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1                                                                                                                            
(pid=4224) 2021-01-25 03:36:38.941347: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1                                                                                                            
(pid=4224) 2021-01-25 03:36:38.983746: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:38.985832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                                                                       
(pid=4224) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                                                              
(pid=4224) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                                
(pid=4224) 2021-01-25 03:36:38.985874: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                                                       
(pid=4224) 2021-01-25 03:36:39.002154: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                                                            
(pid=4224) 2021-01-25 03:36:39.004510: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                       
(pid=4224) 2021-01-25 03:36:39.004943: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                     
(pid=4224) 2021-01-25 03:36:39.016756: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                   
(pid=4224) 2021-01-25 03:36:39.018528: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                                 
(pid=4240) 2021-01-25 03:36:38.982772: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:38.992120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                               
(pid=4240) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                                                              
(pid=4240) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                     
(pid=4240) 2021-01-25 03:36:38.992165: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                 
(pid=4240) 2021-01-25 03:36:38.995011: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                      
(pid=4240) 2021-01-25 03:36:38.997576: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                                                             
(pid=4240) 2021-01-25 03:36:38.998033: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                                                            
(pid=4240) 2021-01-25 03:36:39.025067: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                  
(pid=4240) 2021-01-25 03:36:39.026865: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                                  
(pid=4242) 2021-01-25 03:36:38.987989: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1                                       
(pid=4242) 2021-01-25 03:36:39.012041: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4242) 2021-01-25 03:36:39.012963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                               
(pid=4242) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                                                              
(pid=4242) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                                                           
(pid=4242) 2021-01-25 03:36:39.013001: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                  
(pid=4242) 2021-01-25 03:36:39.015676: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                                                            
(pid=4242) 2021-01-25 03:36:39.032793: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                                                             
(pid=4242) 2021-01-25 03:36:39.033309: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                                 
(pid=4242) 2021-01-25 03:36:39.036205: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                  
(pid=4242) 2021-01-25 03:36:39.037951: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                          
(pid=4224) 2021-01-25 03:36:39.045171: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                                                              
(pid=4224) 2021-01-25 03:36:39.045402: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:39.046448: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:39.047334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                                                                                                      
(pid=4224) 2021-01-25 03:36:39.052366: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
(pid=4224) To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                                                     
(pid=4240) 2021-01-25 03:36:39.049352: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                      
(pid=4240) 2021-01-25 03:36:39.049542: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:39.050535: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:39.051412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                                                         
(pid=4240) 2021-01-25 03:36:39.060409: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA                
(pid=4240) To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                                                                                
(pid=4240) 2021-01-25 03:36:39.090947: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300050000 Hz                                                                             
(pid=4240) 2021-01-25 03:36:39.091310: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561073b9d490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
(pid=4240) 2021-01-25 03:36:39.091339: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version                                                   
(pid=4240) 2021-01-25 03:36:39.091676: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:39.092610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                                                                       
(pid=4240) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                                                                                                           
(pid=4240) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                   
(pid=4240) 2021-01-25 03:36:39.092660: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                               
(pid=4240) 2021-01-25 03:36:39.092714: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                    
(pid=4240) 2021-01-25 03:36:39.092751: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                     
(pid=4240) 2021-01-25 03:36:39.092784: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                    
(pid=4240) 2021-01-25 03:36:39.092828: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                  
(pid=4240) 2021-01-25 03:36:39.092860: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                                  
(pid=4240) 2021-01-25 03:36:39.092894: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                                                              
(pid=4240) 2021-01-25 03:36:39.093015: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:39.093997: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:39.094874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                                                                                                      
(pid=4240) 2021-01-25 03:36:39.094929: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                                                       
(pid=4242) 2021-01-25 03:36:39.068383: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                                                              
(pid=4242) 2021-01-25 03:36:39.068602: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4242) 2021-01-25 03:36:39.069639: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4242) 2021-01-25 03:36:39.070528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                              
(pid=4242) 2021-01-25 03:36:39.075670: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
(pid=4242) To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                                                                                
(pid=4224) Num GPUs Available:  1                                                                                                                                                               
(pid=4240) Num GPUs Available:  1                                                                                                                                                              
(pid=4242) Num GPUs Available:  1                                                                                                                                                              
(pid=4224) 2021-01-25 03:36:39.096224: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300050000 Hz                                                               
(pid=4224) 2021-01-25 03:36:39.096555: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c57517fd50 initialized for platform Host (this does not guarantee that XLA will be used). Devices:                           
(pid=4224) 2021-01-25 03:36:39.096580: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version                                                   
(pid=4224) 2021-01-25 03:36:39.096875: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:39.097840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                                 
(pid=4224) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                     
(pid=4224) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                     
(pid=4224) 2021-01-25 03:36:39.097887: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                          
(pid=4224) 2021-01-25 03:36:39.097938: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                                                            
(pid=4224) 2021-01-25 03:36:39.097974: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                     
(pid=4224) 2021-01-25 03:36:39.098007: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                    
(pid=4224) 2021-01-25 03:36:39.098051: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                  
(pid=4224) 2021-01-25 03:36:39.098085: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                                                                          
(pid=4224) 2021-01-25 03:36:39.098119: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                      
(pid=4224) 2021-01-25 03:36:39.098237: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:39.099211: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:39.100119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                 
(pid=4224) 2021-01-25 03:36:39.100174: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                          
(pid=4242) 2021-01-25 03:36:39.117113: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300050000 Hz                                                                                                        
(pid=4242) 2021-01-25 03:36:39.117446: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5567c8520b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
(pid=4242) 2021-01-25 03:36:39.117469: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version                                                   
(pid=4242) 2021-01-25 03:36:39.117761: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4242) 2021-01-25 03:36:39.287922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                
(pid=4242) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                                                              
(pid=4242) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                                                           
(pid=4242) 2021-01-25 03:36:39.288015: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                                                                                                       
(pid=4242) 2021-01-25 03:36:39.288088: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                                                                                         
(pid=4242) 2021-01-25 03:36:39.288129: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                                  
(pid=4242) 2021-01-25 03:36:39.288165: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                    
(pid=4242) 2021-01-25 03:36:39.288215: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                                                          
(pid=4242) 2021-01-25 03:36:39.288248: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                                                                          
(pid=4242) 2021-01-25 03:36:39.288282: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                                                              
(pid=4242) 2021-01-25 03:36:39.288455: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero                                             
(pid=4242) 2021-01-25 03:36:39.292009: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4242) 2021-01-25 03:36:39.292927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                              
(pid=4242) 2021-01-25 03:36:39.292988: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                               
(pid=4241) 2021-01-25 03:36:39.423960: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1                                       
(pid=4241) 2021-01-25 03:36:39.478878: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:39.484462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                                                                       
(pid=4241) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                                                                                                           
(pid=4241) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                   
(pid=4241) 2021-01-25 03:36:39.484534: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                               
(pid=4241) 2021-01-25 03:36:39.487658: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                    
(pid=4241) 2021-01-25 03:36:39.495579: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                     
(pid=4241) 2021-01-25 03:36:39.496679: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                    
(pid=4241) 2021-01-25 03:36:39.504398: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                  
(pid=4241) 2021-01-25 03:36:39.506988: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                                  
(pid=4241) 2021-01-25 03:36:39.523762: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                                                              
(pid=4241) 2021-01-25 03:36:39.523983: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:39.536776: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:39.537667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                                                                                                      
(pid=4241) 2021-01-25 03:36:39.540574: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
(pid=4241) To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                                                                                
(pid=4241) Num GPUs Available:  1                                                                                                                                                                                                     
(pid=4241) 2021-01-25 03:36:39.581437: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300050000 Hz                                                                                                        
(pid=4241) 2021-01-25 03:36:39.581868: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555ae5ed1520 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
(pid=4241) 2021-01-25 03:36:39.581897: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version                                                                                                                        
(pid=4241) 2021-01-25 03:36:39.582269: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:39.584122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:                                                                 
(pid=4241) pciBusID: 0000:00:1e.0 name: Tesla K80 computeCapability: 3.7                                                                                                                       
(pid=4241) coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s                                                                                    
(pid=4241) 2021-01-25 03:36:39.584178: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                 
(pid=4241) 2021-01-25 03:36:39.584234: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                                                            
(pid=4241) 2021-01-25 03:36:39.584265: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10                                     
(pid=4241) 2021-01-25 03:36:39.584298: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10                                                                            
(pid=4241) 2021-01-25 03:36:39.584347: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10                                    
(pid=4241) 2021-01-25 03:36:39.584383: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10                                 
(pid=4241) 2021-01-25 03:36:39.584416: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7                                        
(pid=4241) 2021-01-25 03:36:39.584547: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:39.585537: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:39.586416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0                                                                 
(pid=4241) 2021-01-25 03:36:39.586473: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1                                  
(pid=4240) 2021-01-25 03:36:40.718731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:                               
(pid=4240) 2021-01-25 03:36:40.718768: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0                                                                                                                                
(pid=4240) 2021-01-25 03:36:40.718788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N                                                                                        
(pid=4242) 2021-01-25 03:36:40.718159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:                                                                       
(pid=4242) 2021-01-25 03:36:40.718209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0                                                                                                                                
(pid=4242) 2021-01-25 03:36:40.718226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N                                                                                        
(pid=4242) 2021-01-25 03:36:40.718569: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:40.722120: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:40.762105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:                                            
(pid=4224) 2021-01-25 03:36:40.762140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0                                                                                        
(pid=4224) 2021-01-25 03:36:40.762158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N                                                                                              (pid=4224) 2021-01-25 03:36:40.762440: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:40.763435: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:40.764421: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4224) 2021-01-25 03:36:40.765731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10235 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capabi
lity: 3.7)                                                                                                                                                                                                                                                         
(pid=4224) 2021-01-25 03:36:40.773515: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c583c590f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(pid=4224) 2021-01-25 03:36:40.773545: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7                                       
(pid=4224) 2021-01-25 03:36:40.775210: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                                                            
(pid=4240) 2021-01-25 03:36:40.728036: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:40.730304: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4240) 2021-01-25 03:36:40.732791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10248 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capabi
lity: 3.7)                                                                                                                                                                                                                            
(pid=4240) 2021-01-25 03:36:40.746814: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561082726600 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(pid=4240) 2021-01-25 03:36:40.746841: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7                                                    
(pid=4240) 2021-01-25 03:36:40.748566: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                    
(pid=4242) 2021-01-25 03:36:40.727951: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4242) 2021-01-25 03:36:40.730117: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4242) 2021-01-25 03:36:40.732037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10249 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capabi
lity: 3.7)                                                                                                                                                                                    
(pid=4242) 2021-01-25 03:36:40.740873: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5567d6d0f3d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(pid=4242) 2021-01-25 03:36:40.740895: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7                                       
(pid=4242) 2021-01-25 03:36:40.742337: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                    
(pid=4241) 2021-01-25 03:36:40.737756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:                               
(pid=4241) 2021-01-25 03:36:40.737788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0                                                                                        
(pid=4241) 2021-01-25 03:36:40.737807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N                                                                                        
(pid=4241) 2021-01-25 03:36:40.738059: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:40.738950: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:40.739799: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(pid=4241) 2021-01-25 03:36:40.740586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10245 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capabi
lity: 3.7)                                                                                                                                                                                                                                                         
(pid=4241) 2021-01-25 03:36:40.751744: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555af4a5e330 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:                           
(pid=4241) 2021-01-25 03:36:40.751775: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7                                                                               
(pid=4241) 2021-01-25 03:36:40.753566: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10                                                                            
(pid=4242) 2021-01-25 03:36:41.052044: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 10.01G (10747837184 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory            
(pid=4242) 2021-01-25 03:36:41.066586: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 9.01G (9673053184 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                                                      
(pid=4242) 2021-01-25 03:36:41.085083: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 8.11G (8705747968 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                         
(pid=4242) 2021-01-25 03:36:41.108080: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 7.30G (7835172864 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory   
(pid=4241) 2021-01-25 03:36:41.090733: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 10.00G (10742908672 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
(pid=4224) 2021-01-25 03:36:41.148257: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 10.00G (10733052160 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
(pid=4242) 2021-01-25 03:36:41.142559: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 6.57G (7051655168 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
(pid=4241) 2021-01-25 03:36:41.114791: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 9.00G (9668618240 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                         
(pid=4241) 2021-01-25 03:36:41.154006: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 8.10G (8701756416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory 
[... this goes on for a long time]
(pid=4241) 2021-01-25 03:36:41.436526: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 3.88G (4162022400 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                         
(pid=4224) 2021-01-25 03:36:41.465043: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 4.30G (4620226048 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                         
(pid=4224) 2021-01-25 03:36:41.498397: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 3.87G (4158203392 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                                                                      
(pid=4242) 2021-01-25 03:36:41.459196: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.83G (3035505664 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                                                      
(pid=4242) 2021-01-25 03:36:41.492853: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.54G (2731954944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory              
(pid=4241) 2021-01-25 03:36:41.470660: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 3.49G (3745820160 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory 
(pid=4241) 2021-01-25 03:36:41.503817: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 3.14G (3371238144 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                         
(pid=4240) Result tf.Tensor(                                                                                                                                                                                                          
(pid=4240) [[22. 28.]                                                                                                                                                                                                                 
(pid=4240)  [49. 64.]], shape=(2, 2), dtype=float32)                                                                                                                                                                                                                               
(pid=4224) 2021-01-25 03:36:41.534231: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 3.49G (3742382848 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                         
(pid=4224) 2021-01-25 03:36:41.567227: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 3.14G (3368144384 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory              
(pid=4242) 2021-01-25 03:36:41.528728: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.29G (2458759424 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory              
(pid=4242) 2021-01-25 03:36:41.561664: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.06G (2212883456 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory 
(pid=4241) 2021-01-25 03:36:41.539730: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.83G (3034114304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                       
[...]
(pid=4224) 2021-01-25 03:36:43.109218: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.49M (2606592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                            
(pid=4241) Result tf.Tensor(                                                                                                                                                                    
(pid=4241) [[22. 28.]                                                                                                                                                                          
(pid=4241)  [49. 64.]], shape=(2, 2), dtype=float32)                                                                                                                                           
(pid=4224) 2021-01-25 03:36:43.120445: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.24M (2345984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory   
(pid=4224) 2021-01-25 03:36:43.132693: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 2.01M (2111488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                            
(pid=4224) 2021-01-25 03:36:43.144294: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 1.81M (1900544 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory    
(pid=4224) 2021-01-25 03:36:43.156832: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 1.63M (1710592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                            
(pid=4224) 2021-01-25 03:36:43.168070: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 1.47M (1539584 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory      
(pid=4224) 2021-01-25 03:36:43.180295: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 1.32M (1385728 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory   
(pid=4224) 2021-01-25 03:36:43.191982: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 1.19M (1247232 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory      
(pid=4224) 2021-01-25 03:36:43.203375: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 1.07M (1122560 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                            
(pid=4224) 2021-01-25 03:36:43.215842: I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 986.8K (1010432 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory                                           
(pid=4224) Result tf.Tensor(                                                                                                                                                                  
(pid=4224) [[22. 28.]                                                                                                                                                                         
(pid=4224)  [49. 64.]], shape=(2, 2), dtype=float32)         
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
I've just seen this error also with `num_gpus=0.24` (throwing errors forever), so it might not be a rounding error after all.

**Comment by simon-mo** [comment]
It's because tensorflow allocate memory for the whole GPU regardless. `max_calls=1` or setting tf memory growth should fix this.

**Comment by simon-mo** [comment]
(Ray doesn't actually constrain the GPU usage, it's just logical research usage)

**Comment by limash** [comment]
Hello! @krfricke @simon-mo

I have similar issues with fractional GPUs. In ray docs there is just "It is the developer’s responsibility to make sure that the individual tasks don’t use more than their share of the GPU memory. TensorFlow can be configured to limit its memory usage."
I adjusted a bit above example to allocate only specific amount of memory.

```
import tensorflow as tf
import ray

parallel_calls = 2

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_virtual_device_configuration(
            gpus[0],
            [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024) 
             for _ in range(parallel_calls)])
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        print(e)

ray.init()


@ray.remote(num_gpus=1/parallel_calls)
def f(device):
    with tf.device(device):
        a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
        c = tf.matmul(a, b)
    print(f"Device: {device}. Result: {c}")


# The four tasks created here can execute concurrently.
ray.get([f.remote(device) for device in logical_gpus])
```

But it faces the similar issues with memory allocation (`CUDA_ERROR_OUT_OF_MEMORY: out of memory`). Max calls=1 and setting tf memory growth do not work either. Could you please provide a working example of how to configure tensorflow to work properly with fractional gpus usage in ray? Thank you!

**Comment by simon-mo** [comment]
Ah for your code snippet. Can you try moving your tf memory config into the task definition? So the tf config runs inside the worker instead of the driver.

**Comment by limash** [comment]
Oh thanks, it works fine.

**Comment by limash** [comment]
> Ah for your code snippet. Can you try moving your tf memory config into the task definition? So the tf config runs inside the worker instead of the driver.

And one more stupid question. Is it guaranteed that different processes won't use the same chunk of memory?

**Comment by richardliaw** [comment]
@limash I think that is true.
