### ISSUE TITLE
NCCL error with RaySGD single node training

### ISSUE THREAD

**Issue by JF-D** [ray-project/ray#16979]
1. Can ray automatically transfer tensors between cpu memory and gpu memory without explicitlly do `tensor.cuda()`?
2. How do ray do cross gpu tensor communication? Can I use nccl to do high performance training?
3. Can I split a model into multiple parts, and ray schedule parts onto different gpus and automatically train the model?
4. I follow the example in https://docs.ray.io/en/master/auto_examples/plot_parameter_server.html and add `@ray.remote(num_gpus=1)` decorator to the server and worker, I discover the throughput is quite low. How can I use ray to do high performance training of DL models (like alexnet) with pytorch?

Thanks a lot!

**Comment by richardliaw** [comment]
Hey @JF-D, nice! 


> Can ray automatically transfer tensors between cpu memory and gpu memory without explicitlly do tensor.cuda()?

Nope, you'll have to manually specify this.

> How do ray do cross gpu tensor communication? Can I use nccl to do high performance training?

You can use NCCL to do this. I would suggest using something like [RaySGD](https://docs.ray.io/en/master/raysgd/raysgd.html) or [Ray Collective Library](https://docs.ray.io/en/master/ray-collective.html), both of which use NCCL 

> Can I split a model into multiple parts, and ray schedule parts onto different gpus and automatically train the model?

There are many ways to do this manually, but it doesn't work directly out of the box; @zhisbug is currently working on something similar. 

> How can I use ray to do high performance training of DL models (like alexnet) with pytorch?

You'll most likely want to use NCCL via distributed pytorch or something similar to get high throughput training.  I do recommend the above-linked RaySGD and Collective Library to do what you're trying to do.

**Comment by JF-D** [comment]
Thanks, Got it!!! @richardliaw 
Are @zhisbug working on auto-parallel training of DL models with ray like FlexFlow which partition models according to layers and operators?

**Comment by richardliaw** [comment]
yep! something along that - still not public!

**Comment by JF-D** [comment]
Great! @richardliaw 
I tried raysgd, and with the example benchmark https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/examples/benchmarks/benchmark.py, I met the following error
![ncclerr](https://user-images.githubusercontent.com/30710061/125190535-45313780-e270-11eb-894a-243fce89ca0c.jpg)
I use pytorch 1.7.1 + cuda-10.1 + nccl 2.7.8. I can run the single card training, but when I run 4 card training, it reports nccl error.
Besides, I didn't use ray cluster, simply, I use `ray.init(num_gpus=4)` to init the ray env.

How can I fix this?

**Comment by richardliaw** [comment]
I think this is definitely a NCCL error -- can you take a look at this to see if it is relevant https://github.com/NVIDIA/nccl/issues/360 ?

**Comment by JF-D** [comment]
That nccl issue is caused by runing processes in different containers, but I run the processes in the same container. This does not seem to be the same problem.

**Comment by richardliaw** [comment]
I would suggest looking around Github to find out the issue. 

https://github.com/PyTorchLightning/pytorch-lightning/issues/4420#issuecomment-739105607
https://github.com/PyTorchLightning/pytorch-lightning/issues/4420#issuecomment-774031331

BTW, you can try setting environment variables within `def init_hook():`.

**Comment by JF-D** [comment]
`export NCCL_P2P_DISABLE=1` does help, but the performance is quite low. It seems it's caused bt p2p init failure...

**Comment by JF-D** [comment]
I checked the argument of `dist.init_process_group`  () of pytorch ddp and raysgd, the only difference is the `init_method`.
In pytorch ddp, `backend, init_method, world_size, world_rank` are the following
![image](https://user-images.githubusercontent.com/30710061/125230216-f8e70580-e30a-11eb-886a-f43885ce5c01.png)
these in raysgd are the following:
![image](https://user-images.githubusercontent.com/30710061/125230322-26cc4a00-e30b-11eb-8511-0f5ee657a274.png)

**Comment by richardliaw** [comment]
Hmm, that's a good catch! we should make it so that the host address for rendezvous is modifiable in TorchTrainer. This would simplify a lot of issues I'm guessing.

By the way, would you be open to pushing a PR? No problem if you're busy - just wanted to offer it.

**Comment by JF-D** [comment]
Sure, although I'm not familiar with Ray yet.

I notice ray set up the process group at an uncommon ip address, why is this address? And I think for single node training, it's better to use localhost address.
![ray](https://user-images.githubusercontent.com/30710061/125234300-01dbd500-e313-11eb-8a71-de088b22f78b.jpg)

**Comment by richardliaw** [comment]
I think we just chose a public ip address, we should make it internal or
localhost for single node  for sure.

**Comment by JF-D** [comment]
Several results:
1. the ip address `10.148.18.24` is the ip of ethnet. It is indeed a public ip address. And  I use this ip address to do pytorch ddp training, it works well. So it is not caused by this.
2. I tried pytorch 1.6 + nccl 2.4.8, raysgd works well. But for pytorch 1.6 / 1.71 + nccl 2.7.8, the nccl error occurs. All cases, pytorch ddp works weel. I think there is something wrong with ray, maybe.

**Comment by richardliaw** [comment]
Can you provide the nccl debug info trace for both Ray and Pytorch?

**Comment by richardliaw** [comment]
Can you also help provide the output of ` nvidia-smi topo -m`?

**Comment by amogkam** [comment]
I think this is the same error as https://github.com/ray-project/ray/issues/15495.

**Comment by JF-D** [comment]
Sorry for my late reply @richardliaw 
Nccl debug info for pytorch
```
ev-duanjiangfei-ap0:34729:34729 [0] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34729:34729 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
dev-duanjiangfei-ap0:34729:34729 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34729:34729 [0] NCCL INFO Using network IB
NCCL version 2.7.8+cuda10.1
dev-duanjiangfei-ap0:34731:34731 [2] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34731:34731 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
dev-duanjiangfei-ap0:34731:34731 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34731:34731 [2] NCCL INFO Using network IB
dev-duanjiangfei-ap0:34730:34730 [1] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34730:34730 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
dev-duanjiangfei-ap0:34730:34730 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34730:34730 [1] NCCL INFO Using network IB
dev-duanjiangfei-ap0:34732:34732 [3] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34732:34732 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
dev-duanjiangfei-ap0:34732:34732 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
dev-duanjiangfei-ap0:34732:34732 [3] NCCL INFO Using network IB
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Channel 00/02 :    0   1   2   3
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Channel 01/02 :    0   1   2   3
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->1|1->2->3/-1/-1
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] -1/-1/-1->3->2|2->3->-1/-1/-1
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 3(=b0)
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO Could not enable P2P between dev 3(=b0) and dev 0(=80)
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO Channel 00 : 2[a0] -> 3[b0] via P2P/IPC
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO Channel 00 : 3[b0] -> 0[80] via direct shared memory
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Channel 00 : 1[90] -> 2[a0] via P2P/IPC
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Channel 00 : 0[80] -> 1[90] via direct shared memory
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO Channel 00 : 3[b0] -> 2[a0] via P2P/IPC
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO Channel 00 : 2[a0] -> 1[90] via P2P/IPC
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Channel 00 : 1[90] -> 0[80] via direct shared memory
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO Could not enable P2P between dev 3(=b0) and dev 0(=80)
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO Channel 01 : 3[b0] -> 0[80] via direct shared memory
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO Channel 01 : 2[a0] -> 3[b0] via P2P/IPC
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 3(=b0)
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Channel 01 : 0[80] -> 1[90] via direct shared memory
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Channel 01 : 1[90] -> 2[a0] via P2P/IPC
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO Channel 01 : 2[a0] -> 1[90] via P2P/IPC
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO Channel 01 : 3[b0] -> 2[a0] via P2P/IPC
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO Channel 01 : 1[90] -> 0[80] via direct shared memory
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dev-duanjiangfei-ap0:34732:34762 [3] NCCL INFO comm 0x7f3d74000e10 rank 3 nranks 4 cudaDev 3 busId b0 - Init COMPLETE
dev-duanjiangfei-ap0:34731:34758 [2] NCCL INFO comm 0x7fe4d8000e10 rank 2 nranks 4 cudaDev 2 busId a0 - Init COMPLETE
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dev-duanjiangfei-ap0:34729:34756 [0] NCCL INFO comm 0x7fd934000e10 rank 0 nranks 4 cudaDev 0 busId 80 - Init COMPLETE
dev-duanjiangfei-ap0:34729:34729 [0] NCCL INFO Launch mode Parallel
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dev-duanjiangfei-ap0:34730:34760 [1] NCCL INFO comm 0x7fcc00000e10 rank 1 nranks 4 cudaDev 1 busId 90 - Init COMPLETE
Use GPU: 3 for training
=> creating model 'alexnet'
Use GPU: 2 for training
=> creating model 'alexnet'
Use GPU: 0 for training
=> creating model 'alexnet'
Use GPU: 1 for training
=> creating model 'alexnet'
```

nccl debug info for ray:
```
2021-07-14 13:21:23,367	INFO services.py:1274 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
[2m[36m(pid=34272)[0m 2021-07-14 13:21:26,887	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:47078 [rank=3]
[2m[36m(pid=34275)[0m 2021-07-14 13:21:26,886	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:47078 [rank=1]
[2m[36m(pid=34268)[0m 2021-07-14 13:21:26,887	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:47078 [rank=2]
[2m[36m(pid=34271)[0m 2021-07-14 13:21:26,886	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:47078 [rank=0]
address to ip: 10.148.18.24 node: 127.0.0.1 address: None
Model: alexnet
Batch size: 128
Number of GPUs: 4
[2m[36m(pid=34272)[0m NCCL DEBUG SET
[2m[36m(pid=34275)[0m NCCL DEBUG SET
[2m[36m(pid=34272)[0m torch dist: nccl tcp://10.148.18.24:47078 4 3 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=34275)[0m torch dist: nccl tcp://10.148.18.24:47078 4 1 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=34268)[0m NCCL DEBUG SET
[2m[36m(pid=34268)[0m torch dist: nccl tcp://10.148.18.24:47078 4 2 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=34271)[0m NCCL DEBUG SET
[2m[36m(pid=34271)[0m torch dist: nccl tcp://10.148.18.24:47078 4 0 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34271 [0] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34271 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34272 [0] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34272 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34272 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34272 [0] NCCL INFO Using network IB
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34275 [0] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34275 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34275 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34275 [0] NCCL INFO Using network IB
[2m[36m(pid=34268)[0m dev-duanjiangfei-ap0:34268:34268 [0] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=34268)[0m dev-duanjiangfei-ap0:34268:34268 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=34268)[0m dev-duanjiangfei-ap0:34268:34268 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=34268)[0m dev-duanjiangfei-ap0:34268:34268 [0] NCCL INFO Using network IB
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34271 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34271 [0] NCCL INFO Using network IB
[2m[36m(pid=34271)[0m NCCL version 2.7.8+cuda10.1
Traceback (most recent call last):
  File "benchmark.py", line 152, in <module>
    use_fp16=args.fp16,
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/torch_trainer.py", line 265, in __init__
    startup_success = self._start_workers(self.max_replicas)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/torch_trainer.py", line 329, in _start_workers
    return self.worker_group.start_workers(num_workers)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/worker_group.py", line 229, in start_workers
    address=address, world_size=num_workers))
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/worker.py", line 1496, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::DistributedTorchRunner.setup_process_group()[39m (pid=34271, ip=10.148.18.24)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 61, in setup_process_group
    url, world_rank, world_size, timeout, backend=self.backend)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/utils.py", line 44, in setup_process_group
    timeout=timeout)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370116979/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] -1/-1/-1->3->2|2->3->-1/-1/-1
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] NCCL INFO Channel 00 : 3[b0] -> 0[80] via P2P/IPC
[2m[36m(pid=34272)[0m 
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] transport/p2p.cc:238 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] NCCL INFO transport.cc:68 -> 1
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] NCCL INFO init.cc:766 -> 1
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] NCCL INFO init.cc:840 -> 1
[2m[36m(pid=34272)[0m dev-duanjiangfei-ap0:34272:34565 [0] NCCL INFO group.cc:73 -> 1 [Async thread]
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] NCCL INFO Channel 00 : 1[90] -> 2[a0] via P2P/IPC
[2m[36m(pid=34275)[0m 
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] transport/p2p.cc:276 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] NCCL INFO transport.cc:79 -> 1
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] NCCL INFO init.cc:766 -> 1
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] NCCL INFO init.cc:840 -> 1
[2m[36m(pid=34275)[0m dev-duanjiangfei-ap0:34275:34567 [0] NCCL INFO group.cc:73 -> 1 [Async thread]
[2m[36m(pid=34268)[0m dev-duanjiangfei-ap0:34268:34566 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=34268)[0m dev-duanjiangfei-ap0:34268:34566 [0] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->1|1->2->3/-1/-1
[2m[36m(pid=34268)[0m dev-duanjiangfei-ap0:34268:34566 [0] NCCL INFO Channel 00 : 2[a0] -> 3[b0] via P2P/IPC
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO Channel 00/02 :    0   1   2   3
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO Channel 01/02 :    0   1   2   3
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO Channel 00 : 0[80] -> 1[90] via P2P/IPC
[2m[36m(pid=34271)[0m 
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] transport/p2p.cc:238 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO transport.cc:68 -> 1
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO init.cc:766 -> 1
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO init.cc:840 -> 1
[2m[36m(pid=34271)[0m dev-duanjiangfei-ap0:34271:34561 [0] NCCL INFO group.cc:73 -> 1 [Async thread]
```
nvidia-sim topo -m
![QQ截图20210714141906](https://user-images.githubusercontent.com/30710061/125572802-49eca95d-761e-4334-b4bb-175c45b39839.jpg)

**Comment by JF-D** [comment]
> I think this is the same error as #15495.
> 
> It's also the same behavior that it works for torch 1.6 and NCCL 2.4.8, but not for torch 1.7.
> 
> For some reason with Pytorch DDP, it's falling back to direct shared memory when P2P is not available, but for RaySGD, this isn't the case.

Indeed. Maybe RaySGD should fix this.

**Comment by richardliaw** [comment]
@JF-D yeah, we should definitely fix it. Thanks for helping provide stack traces, they are very helpful. One last question, can you output CUDA_VISIBLE_DEVICES for pytorch per process started?

**Comment by JF-D** [comment]
The main  process can see all gpus(0,1,2,3), and then use `multiprocesing.spawn` launch 4 process for each gpu. And after launching, each process can also see all gpus.

**Comment by richardliaw** [comment]
OK got it, that may be an issue. In init_hook, can you try setting CUDA
VISIBLE DEVICES to “0,1,2,3”?

**Comment by JF-D** [comment]
After setting CUDA_VISIBLE_DEVICES, it stucks. And here is the log:
```
2021-07-14 16:13:34,614	INFO services.py:1274 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
address to ip: 10.148.18.24 node: 127.0.0.1 address: None
Model: alexnet
Batch size: 128
Number of GPUs: 4
[2m[36m(pid=37108)[0m NCCL DEBUG SET
[2m[36m(pid=37109)[0m NCCL DEBUG SET
[2m[36m(pid=37108)[0m torch dist: nccl tcp://10.148.18.24:40281 4 2 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=37109)[0m torch dist: nccl tcp://10.148.18.24:40281 4 1 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=37103)[0m NCCL DEBUG SET
[2m[36m(pid=37103)[0m torch dist: nccl tcp://10.148.18.24:40281 4 3 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=37105)[0m NCCL DEBUG SET
[2m[36m(pid=37105)[0m torch dist: nccl tcp://10.148.18.24:40281 4 0 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37105 [0] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37105 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37108 [2] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37108 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37108 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37108 [2] NCCL INFO Using network IB
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37109 [1] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37109 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37109 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37109 [1] NCCL INFO Using network IB
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37103 [3] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37103 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37103 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37103 [3] NCCL INFO Using network IB
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37105 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37105 [0] NCCL INFO Using network IB
[2m[36m(pid=37105)[0m NCCL version 2.7.8+cuda10.1
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] -1/-1/-1->3->2|2->3->-1/-1/-1
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Channel 00/02 :    0   1   2   3
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Channel 01/02 :    0   1   2   3
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->1|1->2->3/-1/-1
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO Channel 00 : 2[a0] -> 3[b0] via P2P/IPC
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO Channel 00 : 2[a0] -> 1[90] via P2P/IPC
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO Channel 01 : 2[a0] -> 3[b0] via P2P/IPC
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Channel 00 : 1[90] -> 2[a0] via P2P/IPC
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Channel 00 : 1[90] -> 0[80] via direct shared memory
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Channel 01 : 1[90] -> 2[a0] via P2P/IPC
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO Could not enable P2P between dev 3(=b0) and dev 0(=80)
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO Channel 00 : 3[b0] -> 0[80] via direct shared memory
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO Channel 00 : 3[b0] -> 2[a0] via P2P/IPC
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO Could not enable P2P between dev 3(=b0) and dev 0(=80)
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO Channel 01 : 3[b0] -> 0[80] via direct shared memory
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 3(=b0)
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Channel 00 : 0[80] -> 1[90] via direct shared memory
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 3(=b0)
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Channel 01 : 0[80] -> 1[90] via direct shared memory
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO Channel 01 : 2[a0] -> 1[90] via P2P/IPC
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO Channel 01 : 3[b0] -> 2[a0] via P2P/IPC
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[2m[36m(pid=37108)[0m dev-duanjiangfei-ap0:37108:37388 [2] NCCL INFO comm 0x7f6ee4000e10 rank 2 nranks 4 cudaDev 2 busId a0 - Init COMPLETE
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO Channel 01 : 1[90] -> 0[80] via direct shared memory
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[2m[36m(pid=37109)[0m dev-duanjiangfei-ap0:37109:37387 [1] NCCL INFO comm 0x7f73d0000e10 rank 1 nranks 4 cudaDev 1 busId 90 - Init COMPLETE
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[2m[36m(pid=37103)[0m dev-duanjiangfei-ap0:37103:37390 [3] NCCL INFO comm 0x7f8c14000e10 rank 3 nranks 4 cudaDev 3 busId b0 - Init COMPLETE
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=37105)[0m dev-duanjiangfei-ap0:37105:37384 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
```

**Comment by richardliaw** [comment]
hmm, seems like 2 of them completed. Btw, thanks a lot!

I think we may have enough info to repro ourselves. I suspect there’s a new
environment variable that is missing.

**Comment by amogkam** [comment]
FYI, from the Horovod Docs: https://horovod.readthedocs.io/en/stable/troubleshooting_include.html

> Setting CUDA_VISIBLE_DEVICES has additional disadvantage for GPU version - CUDA will not be able to use IPC, which will likely cause NCCL and MPI to fail. In order to disable IPC in NCCL and MPI and allow it to fallback to shared memory, use: * export NCCL_P2P_DISABLE=1 for NCCL. * --mca btl_smcuda_use_cuda_ipc 0 flag for OpenMPI and similar flags for other vendors.

**Comment by richardliaw** [comment]
Hmm, @JF-D would you be willing to try out one last thing: in `init_hook`, do `os.environ.pop("CUDA_VISIBLE_DEVICES")` so that we unset the visible devices?

**Comment by JF-D** [comment]
Here is the log. It seems nothing different.
```
2021-07-16 14:18:43,036	INFO services.py:1274 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
address to ip: 10.148.18.24 node: 127.0.0.1 address: None
Model: alexnet
Batch size: 128
Number of GPUs: 4
[2m[36m(pid=21065)[0m NCCL DEBUG SET
[2m[36m(pid=21060)[0m NCCL DEBUG SET
[2m[36m(pid=21057)[0m NCCL DEBUG SET
[2m[36m(pid=21065)[0m torch dist: nccl tcp://10.148.18.24:43362 4 1 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=21060)[0m torch dist: nccl tcp://10.148.18.24:43362 4 2 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=21057)[0m torch dist: nccl tcp://10.148.18.24:43362 4 3 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=21062)[0m NCCL DEBUG SET
[2m[36m(pid=21062)[0m torch dist: nccl tcp://10.148.18.24:43362 4 0 /nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/distributed/__init__.py
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21065 [1] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21065 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21060 [2] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21060 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21057 [3] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21057 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21062 [0] NCCL INFO Bootstrap : Using [0]eth0:10.148.18.24<0>
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21062 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21062 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21062 [0] NCCL INFO Using network IB
[2m[36m(pid=21062)[0m NCCL version 2.7.8+cuda10.1
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21065 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21065 [1] NCCL INFO Using network IB
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21060 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21060 [2] NCCL INFO Using network IB
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21057 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.148.18.24<0>
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21057 [3] NCCL INFO Using network IB
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Channel 00 : 1[90] -> 2[a0] via P2P/IPC
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->1|1->2->3/-1/-1
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO Channel 00 : 2[a0] -> 3[b0] via P2P/IPC
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO Channel 00 : 2[a0] -> 1[90] via P2P/IPC
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] -1/-1/-1->3->2|2->3->-1/-1/-1
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO Could not enable P2P between dev 3(=b0) and dev 0(=80)
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO Channel 00 : 3[b0] -> 0[80] via direct shared memory
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Channel 00/02 :    0   1   2   3
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Channel 01/02 :    0   1   2   3
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 3(=b0)
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Channel 00 : 0[80] -> 1[90] via direct shared memory
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Channel 00 : 1[90] -> 0[80] via direct shared memory
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Channel 01 : 1[90] -> 2[a0] via P2P/IPC
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Could not enable P2P between dev 1(=90) and dev 0(=80)
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO Channel 01 : 1[90] -> 0[80] via direct shared memory
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO Channel 01 : 2[a0] -> 3[b0] via P2P/IPC
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO Channel 01 : 2[a0] -> 1[90] via P2P/IPC
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[2m[36m(pid=21060)[0m dev-duanjiangfei-ap0:21060:21343 [2] NCCL INFO comm 0x7eff7c000e10 rank 2 nranks 4 cudaDev 2 busId a0 - Init COMPLETE
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO Channel 00 : 3[b0] -> 2[a0] via P2P/IPC
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO Could not enable P2P between dev 3(=b0) and dev 0(=80)
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO Channel 01 : 3[b0] -> 0[80] via direct shared memory
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO Channel 01 : 3[b0] -> 2[a0] via P2P/IPC
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[2m[36m(pid=21057)[0m dev-duanjiangfei-ap0:21057:21340 [3] NCCL INFO comm 0x7f564c000e10 rank 3 nranks 4 cudaDev 3 busId b0 - Init COMPLETE
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 3(=b0)
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Channel 01 : 0[80] -> 1[90] via direct shared memory
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO Could not enable P2P between dev 0(=80) and dev 1(=90)
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
[2m[36m(pid=21065)[0m dev-duanjiangfei-ap0:21065:21341 [1] NCCL INFO comm 0x7f7464000e10 rank 1 nranks 4 cudaDev 1 busId 90 - Init COMPLETE
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer[2m[36m(pid=21057)[0m 2021-07-16 14:18:46,332	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:43362 [rank=3]
[2m[36m(pid=21060)[0m 2021-07-16 14:18:46,331	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:43362 [rank=2]
[2m[36m(pid=21065)[0m 2021-07-16 14:18:46,331	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:43362 [rank=1]
[2m[36m(pid=21062)[0m 2021-07-16 14:18:46,330	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://10.148.18.24:43362 [rank=0]

[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21337 [0] NCCL INFO comm 0x7f77a0000e10 rank 0 nranks 4 cudaDev 0 busId 80 - Init COMPLETE
[2m[36m(pid=21062)[0m dev-duanjiangfei-ap0:21062:21062 [0] NCCL INFO Launch mode Parallel
Traceback (most recent call last):
  File "benchmark.py", line 156, in <module>
    use_fp16=args.fp16,
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/torch_trainer.py", line 265, in __init__
    startup_success = self._start_workers(self.max_replicas)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/torch_trainer.py", line 329, in _start_workers
    return self.worker_group.start_workers(num_workers)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/worker_group.py", line 233, in start_workers
    ray.get(self._setup_operator())
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/worker.py", line 1496, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::DistributedTorchRunner.setup_operator()[39m (pid=21062, ip=10.148.18.24)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 92, in setup_operator
    scheduler_step_freq=self.scheduler_step_freq)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/training_operator.py", line 148, in __init__
    self.setup(config)
  File "benchmark.py", line 104, in setup
    optimizers=optimizer,
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/training_operator.py", line 327, in register
    ddp_args=ddp_args)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/training_operator.py", line 161, in _configure_ddp
    for model in models
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/ray/util/sgd/torch/training_operator.py", line 161, in <listcomp>
    for model in models
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 410, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 420, in _sync_params_and_buffers
    authoritative_rank)
  File "/nfs/env/miniconda3/envs/pt1.7/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 979, in _distributed_broadcast_coalesced
    self.process_group, tensors, buffer_size, authoritative_rank
RuntimeError: Operation timed out!

```

**Comment by richardliaw** [comment]
@JF-D Hmm, what's your output of `ifconfig`?

**Comment by JF-D** [comment]
![image](https://user-images.githubusercontent.com/30710061/125925965-5bfb711d-c7fa-4a24-a4d3-5f97ca978e3d.png)

**Comment by richardliaw** [comment]
@JF-D thanks for your time; I'll try to repro!

**Comment by richardliaw** [comment]
OK I found out the issue. It looks like if we use a public IP address in dist.init_process_group, the things don't work so well. Specifically, the initialization hangs upon instantiation.

By commenting out L60 in sgd/torch/distributed_torch_runner.py, and then setting the following environment variables in init_hook:
```

def init_hook():
    import torch.backends.cudnn as cudnn
    cudnn.benchmark = True
    import os
    os.environ.pop("CUDA_VISIBLE_DEVICES")
```
and then calling init_process_group manually:
```python
    def setup(self):
        dist.init_process_group(backend="nccl", init_method="tcp://127.0.0.1:29500")
```
I was able to get the performance between DDP and RaySGD to match. Note that: 

1. cuda visible devices needed to be disabled
2. the init method pointed to a localhost address

cc @amogkam @matthewdeng we'll want to check for this in for v2.

**Comment by igorgad** [comment]
Just adding some info here. I was facing the exact same problem but using the `ray_lightning` integration. It seems that it's working with the PyTorch nightly version.

```
pytorch=1.10.0.dev20210817=py3.8_cuda11.1_cudnn8.0.5_0
cudatoolkit=11.1.74=h6bb024c_0
pytorch-lightning==1.4.2
ray-lightning==0.0.1
```

**Comment by amogkam** [comment]
Hey @JF-D, 

We have been developing a new version of Ray SGD with a cleaner API which you can see here: https://docs.ray.io/en/master/raysgd/v2/raysgd.html. This NCCL GPU issue is fixed on Ray SGD v2, so I would recommend you try it out. To easily migrate from Ray SGD v1 to v2 you can check out this guide: https://docs.ray.io/en/master/raysgd/v2/migration-guide.html.

Let me know if you have questions, I am happy to help!
