### ISSUE TITLE
NCCL unhandled cuda error in ray SGD

### ISSUE THREAD

**Issue by davidegraff** [ray-project/ray#17909]
help!

I'm trying to implement multi-GPU training inside some python software I have written and I'm looking to use ray to accomplish this because all other options seem to require running an external script (i.e., all of the Pytorch Distributed documentation uses a specific training script that is invoked.) In contrast, I'm looking to train the model over a distributed setup that is handled entirely internally by the software because the model is then handed to other parts of the code.

I've been using ray successfully to distribute model prediction tasks over GPUs/CPUs in my ray cluster, but am having problems accomplishing the same with model training via ray SGD. Specifically, [this block](https://github.com/coleygroup/molpal/blob/ddp/molpal/models/mpnmodels.py#L164): 
```python
trainer = TorchTrainer(
    training_operator_cls=mpnn.MPNNOperator,
    num_workers=self.num_workers, config=self.train_config,
    use_gpu=self.use_gpu, scheduler_step_freq='batch',
    initialization_hook=initialization_hook
)
```
gives me the following error:
```
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    main()
  File "run.py", line 55, in main
    explorer.run()
  File "/home/degraff/molpal/molpal/explorer.py", line 326, in run
    self.explore_batch()
  File "/home/degraff/molpal/molpal/explorer.py", line 396, in explore_batch
    self._update_model()
  File "/home/degraff/molpal/molpal/explorer.py", line 730, in _update_model
    self.model.train(
  File "/home/degraff/molpal/molpal/models/mpnmodels.py", line 410, in train
    return self.model.train(xs, ys)
  File "/home/degraff/molpal/molpal/models/mpnmodels.py", line 164, in train
    trainer = TorchTrainer(
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 275, in __init__
    startup_success = self._start_workers(self.max_replicas)
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/torch_trainer.py", line 339, in _start_workers
    return self.worker_group.start_workers(num_workers)
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/worker_group.py", line 233, in start_workers
    ray.get(self._setup_operator())
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/worker.py", line 1564, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::DistributedTorchRunner.setup_operator() (pid=2918546, ip=18.18.63.63)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 81, in setup_operator
    self.training_operator = self.training_operator_cls(
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 156, in __init__
    self.setup(config)
  File "/home/degraff/molpal/molpal/models/mpnn/operator.py", line 57, in setup
    self.register(
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 344, in register
    self._models = self._configure_ddp(
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 167, in _configure_ddp
    return [
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/ray/util/sgd/torch/training_operator.py", line 168, in <listcomp>
    DistributedDataParallel(model, device_ids=device_ids, **ddp_args)
  File "/home/degraff/miniconda3/envs/molpal/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 496, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1623448278899/work/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
```

when I define `initialization_hook()` like so:
```python
def initialization_hook():
    print("NCCL DEBUG SET")
    # Need this for avoiding a connection restart issue
    os.environ["NCCL_SOCKET_IFNAME"] = "^docker0,lo"
    os.environ["NCCL_LL_THRESHOLD"] = "0"
    os.environ["NCCL_DEBUG"] = "INFO"
```
I get the following information:
```
(pid=2918546) molgpu01:2918546:2918546 [0] NCCL INFO Bootstrap : Using [0]enp70s0:18.18.63.63<0> [1]vethe9ac691:fe80::8819:afff:fe09:21bb%vethe9ac691<0>
(pid=2918546) molgpu01:2918546:2918546 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
(pid=2918546) molgpu01:2918546:2918546 [0] NCCL INFO NET/IB : No device found.
(pid=2918546) molgpu01:2918546:2918546 [0] NCCL INFO NET/Socket : Using [0]enp70s0:18.18.63.63<0> [1]vethe9ac691:fe80::8819:afff:fe09:21bb%vethe9ac691<0>
(pid=2918546) molgpu01:2918546:2918546 [0] NCCL INFO Using network Socket
(pid=2918546) molgpu01:2918546:2958981 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
(pid=2918546) molgpu01:2918546:2958981 [0] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
(pid=2918546) molgpu01:2918546:2958981 [0] NCCL INFO Channel 00 : 1[21000] -> 0[1000] via P2P/IPC
(pid=2918546) 
(pid=2918546) molgpu01:2918546:2958981 [0] transport/p2p.cc:238 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
(pid=2918546) molgpu01:2918546:2958981 [0] NCCL INFO transport.cc:68 -> 1
(pid=2918546) molgpu01:2918546:2958981 [0] NCCL INFO init.cc:766 -> 1
(pid=2918546) molgpu01:2918546:2958981 [0] NCCL INFO init.cc:840 -> 1
(pid=2918546) molgpu01:2918546:2958981 [0] NCCL INFO group.cc:73 -> 1 [Async thread]
(pid=2918586) molgpu01:2918586:2918586 [0] NCCL INFO Bootstrap : Using [0]enp70s0:18.18.63.63<0> [1]vethe9ac691:fe80::8819:afff:fe09:21bb%vethe9ac691<0>
(pid=2918586) molgpu01:2918586:2918586 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
(pid=2918586) molgpu01:2918586:2918586 [0] NCCL INFO NET/IB : No device found.
(pid=2918586) molgpu01:2918586:2918586 [0] NCCL INFO NET/Socket : Using [0]enp70s0:18.18.63.63<0> [1]vethe9ac691:fe80::8819:afff:fe09:21bb%vethe9ac691<0>
(pid=2918586) molgpu01:2918586:2918586 [0] NCCL INFO Using network Socket
(pid=2918586) NCCL version 2.7.8+cuda11.1
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO Channel 00/02 :    0   1
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO Channel 01/02 :    0   1
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO Channel 00 : 0[1000] -> 1[21000] via P2P/IPC
(pid=2918586) 
(pid=2918586) molgpu01:2918586:2958980 [0] transport/p2p.cc:238 NCCL WARN failed to open CUDA IPC handle : 217 peer access is not supported between these two devices
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO transport.cc:68 -> 1
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO init.cc:766 -> 1
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO init.cc:840 -> 1
(pid=2918586) molgpu01:2918586:2958980 [0] NCCL INFO group.cc:73 -> 1 [Async thread]
```

I have tested in the following environments on a variety of remote clusters:
- ray=1.2, 1.4
- pytorch=1.7, 1.8, 1.9
- cudatoolkit=10.2, 11.1
- OS: CentOS 7
- CUDA version: 10.2, 11.1, 11.4

and the only consistent theme is that it fails when the GPUs are RTX 2080/3080 Ti. When the GPUs are V100s, I have no issue and the NCCL info is like so:
```
(pid=34399) 2021-08-17 17:10:55,737	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.130.56:51211 [rank=1]
(pid=34399) NCCL DEBUG SET
(pid=34536) 2021-08-17 17:10:55,736	INFO distributed_torch_runner.py:58 -- Setting up process group for: tcp://172.31.130.56:51211 [rank=0]
(pid=34536) NCCL DEBUG SET
(pid=34536) d-8-13-1:34536:34536 [0] NCCL INFO Bootstrap : Using [0]ens2f0:172.31.130.56<0>
(pid=34536) d-8-13-1:34536:34536 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
Training:   0%|                                                           | 0/50 [00:00<?, ?epoch/s](pid=34399) d-8-13-1:34399:34399 [0] NCCL INFO Bootstrap : Using [0]ens2f0:172.31.130.56<0>
(pid=34399) d-8-13-1:34399:34399 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
(pid=34399) d-8-13-1:34399:34399 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB ens2f0:172.31.130.56<0>
(pid=34399) d-8-13-1:34399:34399 [0] NCCL INFO Using network IB
(pid=34399) d-8-13-1:34399:6469 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
(pid=34399) d-8-13-1:34399:6469 [0] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
(pid=34399) d-8-13-1:34399:6469 [0] NCCL INFO Setting affinity for GPU 1 to ffff,f00000ff,fff00000
(pid=34399) d-8-13-1:34399:6469 [0] NCCL INFO Channel 00 : 1[d8000] -> 0[86000] via P2P/IPC
(pid=34399) d-8-13-1:34399:6469 [0] NCCL INFO Channel 01 : 1[d8000] -> 0[86000] via P2P/IPC
(pid=34399) d-8-13-1:34399:6469 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
(pid=34399) d-8-13-1:34399:6469 [0] NCCL INFO comm 0x7fd5400032d0 rank 1 nranks 2 cudaDev 0 busId d8000 - Init COMPLETE
(pid=34536) d-8-13-1:34536:34536 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB ens2f0:172.31.130.56<0>
(pid=34536) d-8-13-1:34536:34536 [0] NCCL INFO Using network IB
(pid=34536) NCCL version 2.7.8+cuda11.1
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO Channel 00/02 :    0   1
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO Channel 01/02 :    0   1
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO Setting affinity for GPU 0 to ffff,f00000ff,fff00000
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO Channel 00 : 0[86000] -> 1[d8000] via P2P/IPC
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO Channel 01 : 0[86000] -> 1[d8000] via P2P/IPC
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
(pid=34536) d-8-13-1:34536:6467 [0] NCCL INFO comm 0x7f88540052a0 rank 0 nranks 2 cudaDev 0 busId 86000 - Init COMPLETE
(pid=34536) d-8-13-1:34536:34536 [0] NCCL INFO Launch mode Parallel
```

thanks for the help!

**Comment by richardliaw** [comment]
I think this is probably somewhat similar to https://github.com/ray-project/ray/issues/16979.

We should address this soon in master.

Assigning to Amog and Matthew for now, who are leading the SGD development.

**Comment by davidegraff** [comment]
An additional note: when I run this example from the SGD [getting started page](https://docs.ray.io/en/latest/raysgd/raysgd.html):
```python
import ray
from ray.util.sgd import TorchTrainer
from ray.util.sgd.torch import TrainingOperator
from ray.util.sgd.torch.examples.train_example import LinearDataset

import torch
from torch.utils.data import DataLoader

class CustomTrainingOperator(TrainingOperator):
    def setup(self, config):
        # Load data.
        train_loader = DataLoader(LinearDataset(2, 5), config["batch_size"])
        val_loader = DataLoader(LinearDataset(2, 5), config["batch_size"])

        # Create model.
        model = torch.nn.Linear(1, 1)

        # Create optimizer.
        optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

        # Create loss.
        loss = torch.nn.MSELoss()

        # Register model, optimizer, and loss.
        self.model, self.optimizer, self.criterion = self.register(
            models=model,
            optimizers=optimizer,
            criterion=loss)

        # Register data loaders.
        self.register_data(train_loader=train_loader, validation_loader=val_loader)

def initialization_hook():
    print("NCCL DEBUG SET")
    # Need this for avoiding a connection restart issue
    os.environ["NCCL_SOCKET_IFNAME"] = "^docker0,lo"
    os.environ["NCCL_LL_THRESHOLD"] = "0"
    os.environ["NCCL_DEBUG"] = "INFO"

ray.init()

trainer1 = TorchTrainer(
    training_operator_cls=CustomTrainingOperator,
    num_workers=2, use_gpu=True, config={"batch_size": 64}
    initialization_hook=initialization_hook
)

stats = trainer1.train()
print(stats)
trainer1.shutdown()
print("success!")
```
with 2 GPUs in my ray cluster, it still fails with the same output as above. If I switch to `use_gpu=False` then it works just fine.

**Comment by amogkam** [comment]
Hey @davidegraff, thanks for raising this!

We have been developing a new version of Ray SGD with a cleaner API which you can see here: https://docs.ray.io/en/master/raysgd/v2/raysgd.html. This multi-GPU issue is fixed on Ray SGD v2, so I would recommend you try it out. To easily migrate from Ray SGD v1 to v2 you can check out this guide:  https://docs.ray.io/en/master/raysgd/v2/migration-guide.html.

Let me know if you have questions, I am happy to help!
