### ISSUE TITLE
[RLLIB] Windows WSL GPU Not Detected 

### ISSUE THREAD

**Issue by heinerb** [ray-project/ray#17914]
### What is the problem?
**Problem** The current `ray/lib/python3.9/site-packages/ray/resource_spec.py`  does not support GPU discovery on WSL2.

**Ray Version:** 1.5.1
**OS:** Windows 10/11 WSL2

### Reproduction (REQUIRED)

The current `ray/lib/python3.9/site-packages/ray/resource_spec.py` runs the following check for GPUs. 

```python
import sys
import os
if sys.platform.startswith("linux"):
    proc_gpus_path = "/proc/driver/nvidia/gpus"
    if os.path.isdir(proc_gpus_path):
        result = len(os.listdir(proc_gpus_path))
```

This works for Linux but not WSL2 Linux within Window 10/11 as the selected path does not exist. Can verify that Tensorflow-gpu detects GPU using the following code:

```python
import tensorflow as tf
tf.config.list_physical_devices('GPU')
sys_details = tf.sysconfig.get_build_info()
cuda = sys_details["cuda_version"]
cudnn = sys_details["cudnn_version"]
print(cuda, cudnn)
print(sys_details)
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
print(tf.config.list_physical_devices())
```

The following script is run to verify if GPU can be detected.

```python
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer
tune.run(PPOTrainer,  config={"env": "CartPole-v0", "num_gpus": 0.1})
```

The following script can be run to override detected gpu count.

```python
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer
import ray.resource_spec
import subprocess
ray.resource_spec._autodetect_num_gpus = lambda: 1.0

tune.run(PPOTrainer,  config={"env": "CartPole-v0", "num_gpus": 0.1})
```

Though this does not appear to register GPU process with nvidia-smi as expected. 

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jonathan-laurent** [comment]
I am running into this. Is there a known workaround?

**Comment by juliusfrost** [comment]
I also have this issue. `nvidia-smi` shows I have one in WSL2 and I can run pytorch with GPU as well.

**Comment by juliusfrost** [comment]
This is still an issue.

**Comment by wxy117** [comment]
Still can not detect gpu on windows11 wsl2.

**Comment by XuehaiPan** [comment]
This can be resolved by installing `GPUtil`:

```bash
pip3 install GPUtil
```

https://github.com/ray-project/ray/blob/a31be7cef19502d8e9e2e869e5c8684f919ce66f/python/ray/_private/resource_spec.py#L282-L288

------

Any plan to get CUDA devices from `libcuda.so` directly as I posted in https://github.com/ray-project/ray/issues/17914#issuecomment-1185719516? I can create a PR for it.

`ray` would respect `CUDA_VISIBLE_DEVICES` rather than listing all GPUs from `nvidia-smi` (`GPUtil`). Besides, if the user set an invalid `CUDA_VISIBLE_DEVICES`, no GPUs can be used by CUDA programs, `ray` should detect zero GPU.

```console
$ export CUDA_VISIBLE_DEVICES='0,0'  # duplicate device ordinal is invalid

$ ipython3
```

```python
In [1]: import torch

In [2]: torch.cuda.device_count()
/home/PanXuehai/Miniconda3/envs/ray/lib/python3.9/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 101: invalid device ordinal (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484809662/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Out[2]: 0

In [3]: import ray

In [4]: ray.init()
RayContext(
    ...
)

In [5]: ray.cluster_resources()
Out[5]: {'CPU': 32.0, 'GPU': 1.0, 'node:xxx.xxx.xxx.xxx': 1.0, 'accelerator_type:G': 1.0, 'object_store_memory': 9242200473.0, 'memory': 18484400948.0}
```

**Comment by choosehappy** [comment]
FYI, I had this issue using the ray-ml:latest-gpu docker container on WSL2

As suggested, above, within the docker container i ran:

```pip3 install GPUtil```

and the issue was resolved. 

Seems like this requirement can easily be added to the docker container requirements so that it is installed automatically during image creation?

**Comment by gy2256** [comment]
I still have the same issue. After using the `pip3 install GPUtil` in my docker environment, I still cannot find the GPU

```
>>> ray.cluster_resources()
{'node:172.17.0.3': 1.0, 'memory': 6285675726.0, 'object_store_memory': 3142837862.0, 'CPU': 16.0}
```

**Comment by heinerb** [comment]
This appears to be working in latest versions of ray (tested on ray 2.2.0)
