### ISSUE TITLE
Issue on page /ray-collective.html

### ISSUE THREAD

**Issue by FLYING37520** [ray-project/ray#22764]
This simple code can't run, and throw this error:

Traceback (most recent call last):
  File "/root/autodl-nas/BaseMP/Ray/rayCollectiveInitNccl.py", line 36, in <module>
    results = ray.get([w.compute.remote() for w in workers])
  File "/root/miniconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/worker.py", line 1733, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(NcclError): ray::Worker.compute() (pid=50804, ip=172.17.0.2, repr=<rayCollectiveInitNccl.Worker object at 0x7f4a88476280>)
  File "/root/autodl-nas/BaseMP/Ray/rayCollectiveInitNccl.py", line 18, in compute
    collective.allreduce(self.send, "default")
  File "/root/miniconda3/lib/python3.8/site-packages/ray/util/collective/collective.py", line 267, in allreduce
    g.allreduce([tensor], opts)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 184, in allreduce
    self._collective(tensors, tensors, collective_fn)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 577, in _collective
    comms = self._get_nccl_collective_communicator(key, devices)
  File "/root/miniconda3/lib/python3.8/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 428, in _get_nccl_collective_communicator
    nccl_util.groupEnd()
  File "cupy_backends/cuda/libs/nccl.pyx", line 210, in cupy_backends.cuda.libs.nccl.groupEnd
  File "cupy_backends/cuda/libs/nccl.pyx", line 243, in cupy_backends.cuda.libs.nccl.groupEnd
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_UNHANDLED_CUDA_ERROR: unhandled cuda error

Process finished with exit code 1

envirment:
my mathine is run in a docker rent from autoDL
cupy-cuda113                version:10.2.0
torch1.10.0+cu113
ray1.10.0

**Comment by FLYING37520** [comment]
https://docs.ray.io/en/latest/ray-collective.html?highlight=allreduce#collective-communication

**Comment by yuxiaoba** [comment]
Hello @FLYING37520 ,  I faced the same error,  have you fixed the problem?

**Comment by GEOTCBRL** [comment]
Hello @yuxiaoba , I faced a similar error when I try to initiate a NcclCommunicator in a ray task. Have you fixed the problem?

**Comment by yuxiaoba** [comment]
@GEOTCBRL I have fixed this problem

NcclCommunicator's default communication interface is ib0.  But my server does not have the interface,  I need to modify the default vaule as follow
```
runtime_env = {"env_vars": {"NCCL_SOCKET_IFNAME": "eno4"}}
```

I hope this helps.
