### ISSUE TITLE
[rllib] rllib train.py hangs when using GPUs

### ISSUE THREAD

**Issue by qwerzcxvsadf** [ray-project/ray#3187]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 3.6.2
- **Exact command to reproduce**: python ray/python/ray/rllib/train.py --env Breakout-v4 --run=PPO --config='{"num_workers":16, "num_gpus":5}' --redis-address=<ray head address>

### Describe the problem
I'm testing out a Ray cluster with two nodes (one with 4 CPU threads and 1 GPU, the other with 16 CPU threads and 4 GPUs). Both running CUDA 9.0. Whenever I try running rllib/train.py using the above command it usually hangs with no progress for hours and no indication that it's actually doing anything. Hitting ctrl+c to stop it doesn't work, so I end up hitting ctrl-z and then killing the process. Running from the head node or from a non-head node doesn't seem to make a difference. Also, running from another cluster with the same number of CPUs and GPUs and even the same version of graphics drivers doesn't seem to make a difference either.

### Source code / logs
Sometimes I would get an error like this: "_DeadlockError: deadlock detected by _ModuleLock('ray.rllib.evaluation.sample_batch') at 140686653661704"

Another time I got an error like this: "Dst tensor is not initialized"

Most times it gets stuck on:
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 16/20 CPUs, 5/5 GPUs
Result logdir: /home/user/ray_results/default
RUNNING trials:
 - PPO_Breakout-v4_0:    RUNNING

I can't seem to get the first two cases anymore (these are things I kept note of in previous runs and unfortunately I didn't note the full traceback) as it now only seems to get stuck on the last case. I tried checking the log directory but both progress.csv and result.json are blank and params.json just confirms the CPU and GPU numbers I've set. Is there another log file I should be looking at? Thanks.

**Comment by richardliaw** [comment]
Can you check if this is still the case on master?

**Comment by ericl** [comment]
So the following worked for me after a couple tries on a p3.16xl machine:

`./train.py --run=PPO --env=Breakout-v0 --config='{"num_gpus": 5, "log_level": "DEBUG"}'`

The first few runs it did appear to "hang". I'm not sure why this was, but it seems like once the machine "warmed up" a bit it was fine. This seems to be normal for AWS machines that are freshly started.

One note: with the default batch size, there probably won't be any speedups past 1 gpu. You'll have to increase train_batch_size and sgd_minibatch_size to take advantage of multiple GPUs.

**Comment by ericl** [comment]
One thing you can do is run `ray stack` (new command added in master -- you can install it from the latest wheels: https://ray.readthedocs.io/en/latest/installation.html).

This will show you where things are hanging.

**Comment by qwerzcxvsadf** [comment]
Okay, so I installed ray from the Python 3.6 wheel and tried running the following command:
python python/ray/rllib/train.py --env Breakout-v4 --run=PPO --config='{"num_gpus":6, "log_level":"DEBUG", "train_batch_size":40000}' --num-samples=48 --redis-address=[address]

This gives me the log:

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/84 CPUs, 0/8 GPUs
Memory usage on this node: 2.7/135.1 GB

Created LogSyncer for /home/ddrl/ray_results/default/PPO_Breakout-v4_0_2018-11-19_13-06-39z1180bux -> 
The task with ID 000000001003e4e8ec568e9152253ebe325069b7 is infeasible and cannot currently be executed. It requires {CPU,1.000000},{GPU,6.000000} for execution and {CPU,1.000000},{GPU,6.000000} for placement. Check the client table to view node resources.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/84 CPUs, 6/8 GPUs
Memory usage on this node: 2.8/135.1 GB
Result logdir: /home/ddrl/ray_results/default
PENDING trials:
 - PPO_Breakout-v4_1:	PENDING
 - PPO_Breakout-v4_2:	PENDING
 - PPO_Breakout-v4_3:	PENDING
 - PPO_Breakout-v4_4:	PENDING
 - PPO_Breakout-v4_5:	PENDING
 - PPO_Breakout-v4_6:	PENDING
 - PPO_Breakout-v4_7:	PENDING
 - PPO_Breakout-v4_8:	PENDING
 - PPO_Breakout-v4_9:	PENDING
  ... 29 not shown
 - PPO_Breakout-v4_39:	PENDING
 - PPO_Breakout-v4_40:	PENDING
 - PPO_Breakout-v4_41:	PENDING
 - PPO_Breakout-v4_42:	PENDING
 - PPO_Breakout-v4_43:	PENDING
 - PPO_Breakout-v4_44:	PENDING
 - PPO_Breakout-v4_45:	PENDING
 - PPO_Breakout-v4_46:	PENDING
 - PPO_Breakout-v4_47:	PENDING
RUNNING trials:
 - PPO_Breakout-v4_0:	RUNNING

Then when I run ray stack:
Stack dump for ddrl     20764  0.1  0.1 1751912 151488 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7FD18DBE2700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FD18D3E1700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FD1972F0700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20765  0.1  0.1 1751916 152032 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F83373DB700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F8336BDA700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F8340AE9700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20766  0.1  0.1 1751908 151204 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F0E689E4700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F0E681E3700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F0E720F2700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20767  0.1  0.1 1751916 151416 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F9DC3660700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F9DC2E5F700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F9DCCD6E700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20768  0.1  0.1 1751908 151888 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F4AA36D9700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F4AA2ED8700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F4AACDE7700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20769  0.1  0.1 1751908 151760 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7FB6D283A700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FB6D2039700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FB6DBF48700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20770  0.1  0.1 1751912 151780 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F3C34B6D700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F3C3436C700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F3C3E27B700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20771  0.1  0.1 1751912 151240 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7FAC73337700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FAC72B36700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FAC7CA45700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20772  0.1  0.1 1751912 153940 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F58FE5CB700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F58FDDCA700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F5907CD9700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20773  0.1  0.1 1751912 151360 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F49489D3700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F49481D2700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F49520E1700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20774  0.1  0.1 1751916 151704 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7F2870A4F700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F287024E700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7F287A15D700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)

Stack dump for ddrl     20775  0.1  0.1 1751916 151252 pts/0  Sl   12:48   0:01 ray_worker
Thread 0x7FD959A97700 (active)
	 _periodically_flush_profile_events (ray/profiling.py:97)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FD959296700 (active)
	 recv (redis/_compat.py:79)
	 _read_from_socket (redis/connection.py:174)
	 readline (redis/connection.py:216)
	 read_response (redis/connection.py:284)
	 read_response (redis/connection.py:624)
	 _execute (redis/client.py:2408)
	 parse_response (redis/client.py:2430)
	 listen (redis/client.py:2501)
	 _run (ray/import_thread.py:60)
	 run (threading.py:864)
	 _bootstrap_inner (threading.py:916)
	 _bootstrap (threading.py:884)
Thread 0x7FD9631A5700 (active)
	 _get_next_task_from_local_scheduler (ray/worker.py:988)
	 main_loop (ray/worker.py:1005)
	 <module> (ray/workers/default_worker.py:105)


I don't know where to even start looking.

**Comment by ericl** [comment]
That error means the Ray scheduler refused to place the task. To be sure,
this is a single node which has 8 GPUs right? Rllib requests the GPUs be
colocated on one node so if it's split 4 4 then it can't acquire 6 at once.

**Comment by qwerzcxvsadf** [comment]
This is two nodes, each with 4 GPUs. After posting I noticed the error was different so I deleted the post to go back and check if I needed to do something else first since I don't remember getting that error. Okay, so rllib cannot have the GPU workload split over multiple nodes then? Is there a way to make it do so?

**Comment by ericl** [comment]
Yeah, that's right. Cross node GPU usage has a higher overhead and we
haven't really found a good use case for it yet for RL sized models.

How does performance look as you scale up to 4 GPUs? Is it still the
bottleneck in your training?

**Comment by ericl** [comment]
Ah looking at your workload probably at most 4 GPUs per trial would be
desired? That way tune will run two trials concurrently which will half the
overall experiment time regardless of time per trial. Also you probably
want to increase num workers otherwise simulation will be the bottleneck.
Id try something like num_gpus=1, num_workers=10, maybe also
num_envs_per_worker=5.

**Comment by chaoshunh** [comment]
Eric, can you confirm that Ray RLlib still does't support Cross node GPU usage very well, right?

**Comment by richardliaw** [comment]
RLlib should work fine across GPU nodes.
