### ISSUE TITLE
Release test air_example_dolly_v2_lightning_fsdp_finetuning failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36264]
### What happened + What you expected to happen

The test fails on HEAD of release/2.5.1, even after 3 retries.

Buildkite job:
 - https://buildkite.com/ray-project/release-tests-branch/builds/1773#01889dc2-e443-4732-a46a-a528563a314e

### Versions / Dependencies

releases 2.5.1

### Reproduction script

buildkite

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 160.00 MiB (GPU 0; 14.62 GiB total capacity; 12.10 GiB already allocated; 161.94 MiB free; 13.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

See GRAM usage. Cutting it close already, maybe we could change the instance type?

<img width="992" alt="Screen Shot 2023-06-09 at 9 58 45 AM" src="https://github.com/ray-project/ray/assets/3887863/40cba818-94f7-4ef2-8bc8-5ef90f9032d1">

**Comment by justinvyu** [comment]
Last successful run (6/6/23): https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_58e7xt4ajcw33k6dt2v28x59dl

<img width="904" alt="Screen Shot 2023-06-09 at 10 16 55 AM" src="https://github.com/ray-project/ray/assets/3887863/91d5ddd0-af29-4192-a3bc-3d74afebd6f4">

[dashboard link](https://cld-kvedzwag2qa8i5bjxuevf5i7-grafana.ray.gcp-us-central1-admin.anyscale-test-staging.com/d/dash_0_ses_zq9k1tiu2lbsbiafg8d8uabuxd/default-dashboard-2-5-0rc0?orgId=1&from=1686008250111&to=1686011910721)

**Comment by justinvyu** [comment]
Potential fix: decreasing batch size. Then, let's see what the GRAM utilization is.

**Comment by woshiyyya** [comment]
It passed in release 2.5.0, and the branch cut of release 2.5.1 is Jun 8. The only change between 2.5.0 and 2.5.1 is https://github.com/ray-project/ray/commit/54915ef8d69c800758ba8798370168f07bd37e81, which is unrelated. 

Reducing the batch size from 10 to 8 and kicked off a release test:
https://buildkite.com/ray-project/release-tests-pr/builds/41787#0188a15b-86fa-47b8-a450-30b189f13b40

**Comment by woshiyyya** [comment]
Another potential cause:

In the last successful run:
```python
[INFO] 6/5/2023, 4:23:05 PM: Successfully installed accelerate-0.19.0 lightning-utilities-0.8.0 pytorch_lightning-2.0.2 transformers-4.29.2
```
The Failed run:

```python
[INFO] 6/8/2023, 7:17:11 PM: Successfully installed accelerate-0.20.3 lightning-utilities-0.8.0 pytorch_lightning-2.0.3 safetensors-0.3.1 transformers-4.30.0
```

- pytorch_lightning upgraded from 2.0.2 -> 2.0.3
- transformers upgraded from 4.29.2 -> 4.30.0
Maybe the OOM is because of these library changes. I'll also try to pin the version back and run another release test.

**Comment by ArturNiederfahrenhorst** [comment]
@woshiyyya @justinvyu What's the status of this one? I see related PRs have been merged?

**Comment by woshiyyya** [comment]
@ArturNiederfahrenhorst Yeah. Issue Fixed, I'll close it now.
