### ISSUE TITLE
CUDA_ERROR_INVALID_DEVICE: invalid device ordinal

### ISSUE THREAD

**Issue by raghu1121** [ray-project/ray#3772]
I am running some trials with AHB, it ran perfectly fine on my local ubuntu with GPU, but testing the same program on my university cluster (uses the gpu assigned by SLURM manager) threw the below error for all trials, as result they are not using GPU, but only CPUs. Is it occuring because it is using host name `gpu013` as gpu id? or something else? Any insights what might be going wrong?

Thanks
Raghu

```
Error processing event.
Traceback (most recent call last):
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_worker (pid=42450, host=gpu013)
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 312, in _setup
    self._init()
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 146, in _init
    self.env_creator, self._policy_graph)
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 413, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 533, in _make_evaluator
    output_creator=output_creator)
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 265, in __init__
    self.tf_sess = tf_session_creator()
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 478, in session_creator
    config=tf.ConfigProto(**config["tf_session_args"]))
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/kalyanam/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
```

**Comment by richardliaw** [comment]
How does the SLURM manager allocate trials? is it possible to ssh into one of the nodes allocated by SLURM and try starting a tensorflow GPU session and also checking CUDA_VISIBLE_DEVICES?

**Comment by raghu1121** [comment]
Seems the issue is solved now. I did a couple of things.

1. Added CUDA_VISIBLE_DEVICES
2. Seems i have tensorflow and tensorflow-gpu both installed, uninstalled tensorflow and reinstalled tensorflow-gpu .
3. added Cuda_home path which i previously missed.
4. Used cuda 9.2, previously it was 9.0 and made corresponding changes to LD_LIBRARY_PATH.

I am not sure which solved it, but now it looks good.
