### ISSUE TITLE
[tune] CUDA_ERROR_NO_DEVICE error when use tune.run_experiments()?

### ISSUE THREAD

**Issue by tengteng** [ray-project/ray#4372]
### System information
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.0 dev1
- **Python version**: Anaconda 3.6.4

### Describe the problem
Code below. In training process the logic will invoke a process which will execute a code snippet on GPU. I set CUDA_VISIBLE_DEVICES=0,1,2,3 in my env variable. But that execution code actually throws CUDA_ERROR_NO_DEVICE error.
I suspect [this line](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L995) 
```
ray.utils.set_cuda_visible_devices(ray.get_gpu_ids())
```
Overwrite $CUDA_VISIBLE_DEVICES to [] so simply I tried:
```
ray.init()
ray.get_gpu_ids()
```
and I see it returns an empty list. But I didn't track how this function get invoked by tune.
The reason I connect this issue with ray tune specifically is that when I start training directly from rllib (from @ericl 's suggestion, example below), the training will just run fine.
```
agent = ppo.PPOAgent(env, config)
while XXX:
     agent.train()
```

### Source code / logs
```
if __name__ == '__main__':
    ray.init()
    run_experiments({
        "some_rl": {
            "run": "PPO",
            "env": SomeEnv,
            "resources_per_trial": {
                "cpu": 1,
                "gpu": 1,
            },
            "config": {
                "lr": grid_search([1e-2]),
                'num_workers': 1,
                'num_gpus': 1,
                'num_cpus_per_worker': 1,
                'num_gpus_per_worker': 1,
                'num_cpus_for_driver': 1,
                "env_config": {},
            },
        },
    })
```

**Comment by ericl** [comment]
The following works for me, and I see one GPU visible inside the environment.

```
import os
import numpy as np
import gym
from gym.spaces import Discrete, Box

import ray
from ray.tune import run_experiments, grid_search


class SimpleCorridor(gym.Env):
    def __init__(self, config):
        print("Init corridor: " + os.environ["CUDA_VISIBLE_DEVICES"])
        assert len(ray.get_gpu_ids()) == 1
        self.end_pos = 10
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(
            0.0, self.end_pos, shape=(1, ), dtype=np.float32)

    def reset(self):
        self.cur_pos = 0
        return [self.cur_pos]

    def step(self, action):
        assert action in [0, 1], action
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
        elif action == 1:
            self.cur_pos += 1
        done = self.cur_pos >= self.end_pos
        return [self.cur_pos], 1 if done else 0, done, {}



if __name__ == '__main__':
    ray.init()
    run_experiments({
        "some_rl": {
            "run": "PPO",
            "env": SimpleCorridor,
            "resources_per_trial": {
                "cpu": 1,
                "gpu": 1,
            },
            "config": {
                "lr": grid_search([1e-2]),
                'num_workers': 1,
                'num_gpus': 1,
                'num_cpus_per_worker': 1,
                'num_gpus_per_worker': 1,
                'num_cpus_for_driver': 1,
                "env_config": {},
            },
        },
    })
```

By the way
- You shouldn't set "resources_per_trial" for RLlib -- RLlib will auto-set this, to avoid mistakes.
- If you want to share GPUs with the driver, you can set num_workers: 0.

**Comment by tengteng** [comment]
It works after I removed 'resources_per_trial' and changed 'num_workers' to 0. But I don't understand these options.

> You shouldn't set "resources_per_trial" for RLlib -- RLlib will auto-set this, to avoid mistakes.
So this is specific to tune+RLlib. Can we print a hint message here?

> If you want to share GPUs with the driver, you can set num_workers: 0.
Why setting 'num_worker' as 0 will share GPU resource with the driver?

**Comment by ericl** [comment]
resources_per_trial determines how many resources Tune will allocate from Ray per trial. Normally this is automatically determined based on the other RLlib options.

num_workers is the RLlib parallelism, see this diagram here: https://ray.readthedocs.io/en/latest/rllib-training.html#specifying-resources
