### ISSUE TITLE
[Core] Jax fails within `ray.remote` on GPUs  

### ISSUE THREAD

**Issue by bwohlberg** [ray-project/ray#46684]
### What happened + What you expected to happen

Jax function calls fail within ray remote functions when GPU devices are available (the same code works without any issues with only CPU devices). The primary errors are:
```
E0717 15:59:36.148269 1717904 cuda_dnn.cc:535] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
...
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task
...
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

### Versions / Dependencies

Fails with `ray` 2.32.0 and `jax` versions 0.4.29 and 0.4.30, functions as expected with `jax` 0.4.28.

### Reproduction script

See the example in a [previous issue](https://github.com/ray-project/ray/issues/44087#issuecomment-2010753107) related to `ray` and `jax` interoperability. As-is, this example only functions correctly with CPU devices, but replacing `@ray.remote` on line 5 with `@ray.remote(num_gpus=1)` makes it function correctly with `jax` 0.4.28, but fail with 0.4.29 and 0.4.30.    

### Issue Severity

High: It blocks me from completing my task.

**Comment by bwohlberg** [comment]
This turned out to be purely a `jax` issue. For some reason, when upgrading to 0.4.29 and 0.4.30 using `pip`, the `nvidia-cudnn-cu12` package was not also upgraded as required. Uninstalling all `jax` packages and then re-installing with `pip install jax[cuda12]` correctly triggered the required `nvidia-cudnn-cu12`upgrade.
