### ISSUE TITLE
ray.util.multiprocessing.Pool with CUDA/CuPy

### ISSUE THREAD

**Issue by garrettwrong** [ray-project/ray#48217]
### What happened + What you expected to happen

Hi, I'm encountering an error using Ray `Pool` in a larger application which makes use of a mix of CUDA and CuPy codes.  Inside a Ray `Pool` I call out to one of these libraries and that errors with `cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected`.  I played around with various pool initializations and verified my `nvidia-smi` and `CUDA_VISIBLE_DEVICES` in both the parent and child processes.

I've reduced the problem down to a tiny small example.

Probably I'm not setting this up correctly and am hoping someone can give me a quick fix.  Unfortunately if I can't make this work with Ray I'll probably need to remove Ray from our package in favor of increasing our implementations of GPU solutions.

Thanks!

### Versions / Dependencies

ray==2.37.0
Python 3.12.7
el9
cupy-cuda12x==13.3.0

### Reproduction script

```
import cupy as cp
from ray.util.multiprocessing import Pool

def f(index):
    a = cp.arange(10)
    return a*index

pool = Pool(2)
for result in pool.map(f, range(10)):
    print(result)
```

`nvidia-smi`

```
Wed Oct 23 11:28:56 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          On  |   00000000:17:00.0 Off |                    0 |
| N/A   34C    P0             36W /  250W |     773MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-PCIE-40GB          On  |   00000000:CA:00.0 Off |                    0 |
| N/A   35C    P0             38W /  250W |       4MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    289943      C   ...al/Matlab/R2023a/bin/glnxa64/MATLAB          0MiB |
+-----------------------------------------------------------------------------------------+
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by garrettwrong** [comment]
To clarify, I am not wishing to perform any multi-GPU computation at this time.  Rather I would like each pool member to have access to the default GPU.

Most of the time (spare a few custom CUDA kernels) the application does not fully utilize a large GPU and we are mixing with host only code that benefits from multiprocessing (hence why we are using the Ray Pool).

Thanks

**Comment by wingkitlee0** [comment]
it looks like ray's `Pool` does not support GPU now. Are you able to use `@ray.remote`?
The following code works for me:
```
import cupy as cp
import ray

@ray.remote(num_gpus=1)
def f(x):
    a = cp.arange(10)
    result = a * x
    return cp.asnumpy(result)

results = ray.get([f.remote(i) for i in range(5)])

print(results)
```

**Comment by garrettwrong** [comment]
Hi, thanks for confirming Ray Pool does not work with CuPy at this time.  That's unfortunate.

I may be able refactor my application to use the `ray.remote` decorator, but it requires a little more refactoring than I would prefer and I am also having to raise `FUNCTION_SIZE_ERROR_THRESHOLD`. (Using ray.put() with shared arrays was not enough...).  These are not directly related to Pool not working, so I'll close this issue.  Thanks.

**Comment by wingkitlee0** [comment]
Came across `Pool` the other day: `num_gpus` needs to be specified:

```
In [1]: import ray

In [2]: ray.init(num_gpus=1)
2025-04-05 23:21:27,094 INFO worker.py:1843 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
Out[2]: RayContext(dashboard_url='127.0.0.1:8265', python_version='3.12.9', ray_version='2.44.1', ray_commit='daca7b2b1a950dc7f731e34e74c76ae383794ffe')

In [3]: import cupy as cp
   ...: from ray.util.multiprocessing import Pool
   ...: 
   ...: def f(index):
   ...:     a = cp.arange(10)
   ...:     return a*index
   ...: 
   ...: pool = Pool(2, ray_remote_args={"num_gpus": 0.5})
   ...: for result in pool.map(f, range(10)):
   ...:     print(result)
   ...: 
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  4  8 12 16 20 24 28 32 36]
[ 0  5 10 15 20 25 30 35 40 45]
[ 0  6 12 18 24 30 36 42 48 54]
[ 0  7 14 21 28 35 42 49 56 63]
[ 0  8 16 24 32 40 48 56 64 72]
[ 0  9 18 27 36 45 54 63 72 81]
```
