### ISSUE TITLE
invalid device ordinal when update Ray version

### ISSUE THREAD

**Issue by Rus-P** [ray-project/ray#58449]
### What happened + What you expected to happen

When I ran vllm v0.10.2 with ray==2.48.0, it crashed with **torch.AcceleratorError: HIP error: invalid device ordinal**. After debugging, I found out that there is only one device is visible to vllm which should be 16. But if I downgrade ray version to 2.44.1, it worked.

It can work on single node with 8 devices, but crashed on 2 nodes.

I know there is env like RAY_EXPERIMENTAL_NOSET_HIP_VISIBLE_DEVICES can solve related problem, but it doesn't work for my case.

```
ERROR 11-07 09:43:49 [core.py:718] EngineCore failed to start.
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718] Traceback (most recent call last):
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 709, in run_engine_core
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 505, in __init__
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 82, in __init__
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 264, in __init__
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     super().__init__(*args, **kwargs)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     self._init_executor()
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/executor/ray_distributed_executor.py", line 50, in _init_executor
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     super()._init_executor()
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/ray_distributed_executor.py", line 107, in _init_executor
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     self._init_workers_ray(placement_group)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/ray_distributed_executor.py", line 379, in _init_workers_ray
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     self._run_workers("init_device")
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/ray_distributed_executor.py", line 505, in _run_workers
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     ray_worker_outputs = ray.get(ray_worker_outputs)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     return fn(*args, **kwargs)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     return func(*args, **kwargs)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/ray/_private/worker.py", line 2961, in get
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     values, debugger_breakpoint = worker.get_objects(
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]                                   ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/ray/_private/worker.py", line 1026, in get_objects
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     raise value.as_instanceof_cause()
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718] ray.exceptions.RayTaskError(AcceleratorError): ray::RayWorkerWrapper.execute_method() (pid=53184, ip=192.168.23.3, actor_id=8f87b64b1254d4976001a34601000000, repr=<vllm.executor.ray_utils.RayWorkerWrapper object at 0x76caa4f254f0>)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 628, in execute_method
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     raise e
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 619, in execute_method
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     return run_method(self, method, args, kwargs)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3060, in run_method
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     return func(*args, **kwargs)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 611, in init_device
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     self.worker.init_device()  # type: ignore
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 168, in init_device
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     current_platform.set_device(self.device)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/vllm/platforms/rocm.py", line 262, in set_device
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     torch.cuda.set_device(device)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]   File "/opt/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 569, in set_device
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718]     torch._C._cuda_setDevice(device)
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718] torch.AcceleratorError: HIP error: invalid device ordinal
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718] HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718] For debugging consider passing AMD_SERIALIZE_KERNEL=3
(EngineCore_DP0 pid=53002) ERROR 11-07 09:43:49 [core.py:718] Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

```

### Versions / Dependencies

rocm7.1
ray2.48.0
vllm 0.10.2
2 nodes with 16 R9700

### Reproduction script

```python
VLLM_WORKER_MULTIPROC_METHOD=spawn 
vllm serve /home/amd/model2/Qwen3-235B-A22B-Instruct-2507/ \
--block-size 16 \
--enable-chunked-prefill  \
--max-num-batched-tokens 256  \
--max-num-seqs 256  \
--max-model-len 8192  \
--trust-remote-code  \
-tp 8 -pp 2  \
--distributed-executor-backend ray  
```

### Issue Severity

None

**Comment by secondspass** [comment]
I also encounter this when I was experimenting with running vLLM 0.11 with ray 2.51.1, trying to serve [gemma-3-27b-it](https://huggingface.co/google/gemma-3-27b-it) across 4 nodes. The solution was to explicitly set CUDA_VISIBLE_DEVICES instead, AND also unset ROCR_VISIBLE_DEVICES if that is set (if ROCR_VISIBLE_DEVICES is set, it will complain that you should set HIP_VISIBLE_DEVICES which as we see runs into the invalid ordinal error).

**Comment by Rus-P** [comment]
> I also encounter this when I was experimenting with running vLLM 0.11 with ray 2.51.1, trying to serve [gemma-3-27b-it](https://huggingface.co/google/gemma-3-27b-it) across 4 nodes. The solution was to explicitly set CUDA_VISIBLE_DEVICES instead, AND also unset ROCR_VISIBLE_DEVICES if that is set (if ROCR_VISIBLE_DEVICES is set, it will complain that you should set HIP_VISIBLE_DEVICES which as we see runs into the invalid ordinal error).

Thank you so much for your replying, but explicitly set CUDA_VISIBLE_DEVICES still can not solve my problem.

**Comment by Rus-P** [comment]
> I also encounter this when I was experimenting with running vLLM 0.11 with ray 2.51.1, trying to serve [gemma-3-27b-it](https://huggingface.co/google/gemma-3-27b-it) across 4 nodes. The solution was to explicitly set CUDA_VISIBLE_DEVICES instead, AND also unset ROCR_VISIBLE_DEVICES if that is set (if ROCR_VISIBLE_DEVICES is set, it will complain that you should set HIP_VISIBLE_DEVICES which as we see runs into the invalid ordinal error).

It turns out I have to explicitly set CUDA_VISIBLE_DEVICES before starting ray connect, my case successfully run through 2 nodes right now ! Thanks again.

**Comment by leoyuppieqnew** [comment]
> > I also encounter this when I was experimenting with running vLLM 0.11 with ray 2.51.1, trying to serve [gemma-3-27b-it](https://huggingface.co/google/gemma-3-27b-it) across 4 nodes. The solution was to explicitly set CUDA_VISIBLE_DEVICES instead, AND also unset ROCR_VISIBLE_DEVICES if that is set (if ROCR_VISIBLE_DEVICES is set, it will complain that you should set HIP_VISIBLE_DEVICES which as we see runs into the invalid ordinal error).
> 
> It turns out I have to explicitly set CUDA_VISIBLE_DEVICES before starting ray connect, my case successfully run through 2 nodes right now ! Thanks again.

Hello, I encountered the same problem, but setting CUDA_VISIBLE_DEVICES didn't work. Could you please tell me how you set it? Thanks

**Comment by secondspass** [comment]
This is what I do in the script I have that starts the ray head node and worker nodes
```
export CUDA_VISIBLE_DEVICES=$ROCR_VISIBLE_DEVICES
unset ROCR_VISIBLE_DEVICES
```
That seemed to get it working.

**Comment by Rus-P** [comment]
> > > I also encounter this when I was experimenting with running vLLM 0.11 with ray 2.51.1, trying to serve [gemma-3-27b-it](https://huggingface.co/google/gemma-3-27b-it) across 4 nodes. The solution was to explicitly set CUDA_VISIBLE_DEVICES instead, AND also unset ROCR_VISIBLE_DEVICES if that is set (if ROCR_VISIBLE_DEVICES is set, it will complain that you should set HIP_VISIBLE_DEVICES which as we see runs into the invalid ordinal error).
> > 
> > 
> > It turns out I have to explicitly set CUDA_VISIBLE_DEVICES before starting ray connect, my case successfully run through 2 nodes right now ! Thanks again.
> 
> Hello, I encountered the same problem, but setting CUDA_VISIBLE_DEVICES didn't work. Could you please tell me how you set it? Thanks

It depends on your rocm version, if you are using rocm>=7.0, just explicitly set CUDA_VISIBLE_DEVICES before starting ray connect, if you are using rocm<7.0, like 6.4, try RAY_EXPERIMENTAL_NOSET_ROCR_VISIBLE_DEVICES=1 and RAY_EXPERIMENTAL_NOSET_HIP_VISIBLE_DEVICES=1
