### ISSUE TITLE
Colab slows dramatically as dataset increases using ray.put/get

### ISSUE THREAD

**Issue by stanlee1986** [ray-project/ray#6072]
### System information
- Ubuntu 18.04.3 LTS Google Colab
- binary
- ray-0.8.0.dev5-cp36-cp36m-manylinux1_x86_64
- Python 3.6.8

With train and test data totaling (2850000, 43) in four arrays initialization and each iteration of a trial is ~10x  slower (300s 30s per iter as attached) if I use ray.put/get vs loading directly from memory into each trial. I can't test the difference in speed at larger sizes because redis limits you to 500MB transfers, but I have yet to get tune to complete an iteration of a trial using ray.put/get at larger sizes. I'm guessing this is an interaction with colab? the [colab notebook](https://colab.research.google.com/drive/1BdZi55iOWpokENhKEVXlmjTKlbK9sX1r) can be cloned and run as is in colab. Make sure to use a gpu high memory runtime to avoid any possibility of running out of memory (run out of memory in regular gpu to be offered high memory).

```
x_train = np.random.random(size=(3000000,42))
...
ray.init()
...
xts = ray.put(x_train)
...
def tune_isis(config):
...
model.fit(ray.get(xts), ...

```
vs

```
ray.init()
...
def tune_isis(config):
...
model.fit(x_train, ...
```

### Source code / logs
```
#COMMENT OUT whole block if not colab
restart = False
try:
  import ray
except:

  print("Setting up colab environment")
  !pip uninstall -y -q pyarrow
  !pip install -q https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.8.0.dev5-cp36-cp36m-manylinux1_x86_64.whl
  !pip install -q ray[debug]
  restart = True

if restart:
  print("Done installing! Restarting via forced crash (this is not an issue).")
  import os
  os._exit(0)

import os
os.environ['MKL_NUM_THREADS'] = '1'
import numpy as np
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler, Binarizer, OneHotEncoder
x_train = np.random.random(size=(3000000,42))
y_train = np.random.randint(0,3,size=(3000000,1))
x_val = np.random.random(size=(850000,42))
y_val = np.random.randint(0,3,size=(850000,1))
scaler = RobustScaler().fit(x_train)
x_train, x_val = scaler.transform(x_train), scaler.transform(x_val)
#works when shrunk but still very slow at this size
x_train, y_train, x_val, y_val = x_train[:2000000], y_train[:2000000], x_val[:850000], y_val[:850000]
y_train = OneHotEncoder(dtype = np.int8, sparse=False, categories='auto').fit_transform(y_train.reshape(-1,1))
y_val = OneHotEncoder(dtype = np.int8, sparse=False, categories='auto').fit_transform(y_val.reshape(-1,1))

#COMMENT OUT %tf_version... if not on colab
%tensorflow_version 2.x

def create_model(learning_rate, dense_1, dense_2, loss):
    
    import numpy as np
    np.random.seed(0)

    import tensorflow as tf
    try:
        tf.get_logger().setLevel('INFO')
    except Exception as exc:
        print(exc)
    import warnings
    warnings.simplefilter("ignore")

    assert learning_rate > 0 and dense_1 > 0 and dense_2 > 0, "Did you set the right configuration?"
    l = tf.keras.layers
    source = tf.keras.Input(shape=(42))
    x = l.Flatten()(source)
    x = l.Dense(int(dense_1), kernel_initializer='normal', activation='relu')(x)
    x = l.Dropout(rate = 0.5)(x)
    x = l.Dense(int(dense_2), kernel_initializer='normal', activation='relu')(x)
    predictions = l.Dense(3, kernel_initializer='normal', activation='softmax')(x)

    model = tf.keras.Model(inputs=[source], outputs=[predictions])
    opt = tf.keras.optimizers.Adam(lr=learning_rate, epsilon=0.1)
    model.compile(loss=loss, optimizer=opt, metrics=['accuracy'])
    return model

import tensorflow.keras as keras
from ray.tune import track


class TuneReporterCallback(keras.callbacks.Callback):
    """Tune Callback for Keras.
    
    The callback is invoked every epoch.
    """

    def __init__(self, logs={}):
        self.iteration = 0
        super(TuneReporterCallback, self).__init__()

    def on_epoch_end(self, batch, logs={}):
        self.iteration += 1
        track.log(keras_info=logs, mean_loss=logs.get("loss"), mean_accuracy=logs.get("val_acc"))

class Stopper:
    def __init__(self):
        self.should_stop = False

    def stop(self, trial_id, result):
        if not self.should_stop and ((result["keras_info/val_acc"] > result["keras_info/acc"]) & (result["training_iteration"] > 2)):
            self.should_stop = True
        return self.should_stop

import inspect
from ray import tune
from tensorflow.keras.callbacks import ModelCheckpoint
def tune_iris(config):  # TODO: Change me.
    import numpy as np
    model = create_model(learning_rate=config["lr"], dense_1=config["dense_1"], dense_2=config["dense_2"], loss=config["loss"])  # TODO: Change me.
    checkpoint_callback = ModelCheckpoint(
        "model.h5", monitor='val_acc', save_best_only=True)
    
    # Enable Tune to make intermediate decisions by using a Tune Callback hook. This is Keras specific.
    callbacks = [checkpoint_callback, TuneReporterCallback()]
    
    #Load via ray object store
    model.fit(
        ray.get(xts), ray.get(yts),
        validation_data = (ray.get(xvs), ray.get(yvs)),
        verbose=2, epochs=10, callbacks=callbacks,
        batch_size=20)
    
    #Load directly from memory via Redis
    '''model.fit(
        x_train, y_train,
        validation_data = (x_val, y_val),
        verbose=2, epochs=10, callbacks=callbacks,
        batch_size=20)'''
    return model

import numpy as np; np.random.seed(42)
import ray
import pandas as pd
hyperparameter_space = {"lr": tune.loguniform(0.001, 0.1),  
    "dense_1": tune.uniform(2, 100),
    "dense_2": tune.uniform(2, 100),
    "loss": tune.grid_search(['categorical_crossentropy'])}  
num_samples = 10 

ray.shutdown()  # Restart Ray defensively in case the ray connection is lost. 
ray.init(log_to_driver=False, num_cpus=4, num_gpus=0)

xts = ray.put(x_train)
yts = ray.put(y_train)
xvs = ray.put(x_val)
yvs = ray.put(y_val)

stopper = Stopper()

analysis = tune.run(
    tune_iris,
    verbose=1, 
    config=hyperparameter_space,
    stop=stopper.stop,
    num_samples=num_samples)
```

**Comment by richardliaw** [comment]
I'm actually guessing that this is a problem with using shared memory on Colab. Can you try copying it out of shared memory?

```
array = ray.get(x).copy()
```

**Comment by stanlee1986** [comment]
ray.get(x).copy() had no effect, but increasing model.fit(batch_size) to 1024 brought it back close to parity and 16384 made it essentially equal. In contrast a non-Tune version has no change in speed to increasing batch_size. This also works with larger datasets so I'm guessing the issue was that ray's way of handling memory can't keep small tf models fed with low batch sizes. This may or may not be colab specific.
