### ISSUE TITLE
[rllib] custom torch model with torch.cuda.FloatTensor and torch.FloatTensor

### ISSUE THREAD

**Issue by esquires** [ray-project/ray#7583]
### What is your question?

I am trying to implement a custom torch model and am using `ray/rllib/models/torch/visionnet.py` as a template. It looks like sometimes the observation provided to the forward function is a cuda tensor and sometimes not.  

My first iteration of this called `.cuda()` when constructing the convolutional/fully connected layers. This creates a problem when the input observation is on the cpu discussed [here](https://github.com/ray-project/ray/issues/3265). I tried setting `num_gpus_per_worker` but that seemed the wrong approach since I didn't have to do that for tensorflow models. It also works when `num_workers = 0` but I'd like to have more workers than that.

My second iteration was to not calll `.cuda()` when constructing convolutional/fully connected layers. However, it looks like there occasions where `forward` is called where the input is on the gpu. Obviously, I can put the input on a cpu in this case but this seems inefficient if it is already on the gpu.

My question is how should I change the model in order to leverage the gpu so that it can avoid the above errors. Here is a minimal working example. Set `use_custom_torch_model = False` to run with `visionnet.py` without errors. Set `call_cuda = True` to see the cuda error.

```python
import numpy as np

import ray
from ray.rllib.models.torch.torch_modelv2 import TorchModelV2
from ray.rllib.models.torch.misc import valid_padding, SlimConv2d, SlimFC
from ray.rllib.utils.annotations import override
from ray.rllib.utils import try_import_torch

torch, nn = try_import_torch()


class CustomTorchModel(nn.Module, TorchModelV2):
    def __init__(
            self, obs_space, action_space, num_outputs, model_config, name):

        TorchModelV2.__init__(
            self, obs_space, action_space, num_outputs, model_config, name)

        nn.Module.__init__(self)

        filters = [16, 32, 32, 32]
        conv_kernel = [3, 3]
        conv_stride = [1, 1]
        call_cuda = False

        (w, h, in_channels) = obs_space.shape
        in_size = [w, h]
        self.convs = []
        for out_channels in filters:
            padding, out_size = valid_padding(
                in_size, filter_size=conv_kernel, stride_size=conv_stride)

            # note: xavier initialization is handled in SlimConv2d
            self.convs.append(SlimConv2d(
                in_channels, out_channels, kernel=conv_kernel,
                stride=conv_stride, padding=padding, activation_fn=None))

            if call_cuda:
                self.convs[-1].cuda()

            in_channels = out_channels
            in_size = out_size

        in_size = int(filters[-1] * np.prod(in_size))

        linear = SlimFC(
            in_size, 256, nn.init.xavier_uniform_, activation_fn=nn.ReLU)

        if call_cuda:
            linear.cuda()

        self.fc = nn.Sequential(nn.Flatten(), nn.ReLU(), linear)

        self.pi_layer = SlimFC(
            256, num_outputs, nn.init.xavier_uniform_, activation_fn=None)
        self.v_layer = SlimFC(
            256, 1, nn.init.xavier_uniform_, activation_fn=None)

        if call_cuda:
            self.fc.cuda()
            self.pi_layer.cuda()
            self.v_layer.cuda()

        self._cur_value = None

    @override(TorchModelV2)
    def forward(self, input_dict, state, seq_lens):
        x = input_dict['obs'].float()

        # put channel in second dim
        x = x.permute(0, 3, 1, 2)
        for conv in self.convs:
            x = conv(x)

        x = self.fc(x)
        logits = self.pi_layer(x)
        self._cur_value = self.v_layer(x).squeeze(1)
        self._last_output = logits
        return logits, state

    @override(TorchModelV2)
    def value_function(self) -> torch.tensor:
        assert self._cur_value is not None, "must call forward() first"
        return self._cur_value


def main() -> None:
    use_custom_torch_model = True
    ray.rllib.models.ModelCatalog.register_custom_model(
        "CustomTorchModel", CustomTorchModel)

    config = {
        'env': 'Pong-v0',
        'num_gpus': 1,
        'num_workers': 1,
        'use_pytorch': True
    }

    if use_custom_torch_model:
        config['model'] = {'custom_model': 'CustomTorchModel'}

    ray.tune.run('PPO', config=config)


if __name__ == '__main__':
    main()
```

Here is the error I get when running the above code. I'll note that the forward pass completes successfully many times before the error occurs because in the successful forward passes the input is on the cpu:

```
Failure # 1 (occurred at 2020-03-12_08-38-02)
Traceback (most recent call last):
  File "/home/esquires/repos/rl/smarl/ray/python/ray/tune/trial_runner.py", line 459, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/tune/ray_trial_executor.py", line 377, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/worker.py", line 1486, in get    
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ^[[36mray::PPO.train()^[[39m (pid=11760, ip=10.108.21.141)
  File "python/ray/_raylet.pyx", line 444, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 422, in ray._raylet.execute_task.function_executor
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/agents/trainer.py", line 500, in train
    raise e
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/agents/trainer.py", line 486, in train
    result = Trainable.train(self)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/tune/trainable.py", line 254, in train
    result = self._train()
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/agents/trainer_template.py", line 148, in _train
    fetches = self.optimizer.step()
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/optimizers/sync_samples_optimizer.py", line 71, in step
    self.standardize_fields)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/utils/sgd.py", line 111, in do_minibatch_sgd
    }, minibatch.count)))[policy_id]
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/evaluation/rollout_worker.py", line 629, in learn_on_batch
    info_out[pid] = policy.learn_on_batch(batch)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/policy/torch_policy.py", line 132, in learn_on_batch
    loss_out = self._loss(self, self.model, self.dist_class, train_batch)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/agents/ppo/ppo_torch_policy.py", line 115, in ppo_surrogate_loss
    logits, state = model.from_batch(train_batch)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/models/modelv2.py", line 193, in from_batch
    return self.__call__(input_dict, states, train_batch.get("seq_lens"))
  File "/home/esquires/anaconda3/envs/smarl_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "torch_err.py", line 73, in forward
    x = conv(x)
  File "/home/esquires/anaconda3/envs/smarl_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/esquires/repos/rl/smarl/ray/python/ray/rllib/models/torch/misc.py", line 89, in forward
    return self._model(x)
  File "/home/esquires/anaconda3/envs/smarl_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/esquires/anaconda3/envs/smarl_torch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/esquires/anaconda3/envs/smarl_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/esquires/anaconda3/envs/smarl_torch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/esquires/anaconda3/envs/smarl_torch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```
*Ray version and other system information (Python version, TensorFlow version, OS):*

* ray version: releases/0.8.3 (sha 589476f5) built from source
* torch version: 1.4.0
* OS: Ubuntu 18.04
* Python: 3.7.6 (using anaconda)

**Comment by ericl** [comment]
The reason it's sometimes on GPU and not is due to inference (rollouts, on CPU unless workers are configured with GPUs) vs training (GPU).

To detect the difference, you can check `torch.cuda.is_available()`, or otherwise try writing the model in a way that it works with both (TorchPolicy will call `model.to(device)` to the right device after the model is created).

@sven1977 correct me if there's an easier way here.

**Comment by esquires** [comment]
Thanks! That works for me.
